// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class webgpu_h$shared {

    webgpu_h$shared() {
        // Should not be called directly
    }

    public static final ValueLayout.OfBoolean C_BOOL = (ValueLayout.OfBoolean) Linker.nativeLinker().canonicalLayouts().get("bool");
    public static final ValueLayout.OfByte C_CHAR =(ValueLayout.OfByte)Linker.nativeLinker().canonicalLayouts().get("char");
    public static final ValueLayout.OfShort C_SHORT = (ValueLayout.OfShort) Linker.nativeLinker().canonicalLayouts().get("short");
    public static final ValueLayout.OfInt C_INT = (ValueLayout.OfInt) Linker.nativeLinker().canonicalLayouts().get("int");
    public static final ValueLayout.OfLong C_LONG_LONG = (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long long");
    public static final ValueLayout.OfFloat C_FLOAT = (ValueLayout.OfFloat) Linker.nativeLinker().canonicalLayouts().get("float");
    public static final ValueLayout.OfDouble C_DOUBLE = (ValueLayout.OfDouble) Linker.nativeLinker().canonicalLayouts().get("double");
    public static final AddressLayout C_POINTER = ((AddressLayout) Linker.nativeLinker().canonicalLayouts().get("void*"))
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, C_CHAR));
    // HAND-EDITED, and the edit must survive any jextract regeneration.
    //
    // jextract emitted `(ValueLayout.OfLong) canonicalLayouts().get("long")` here. That holds on
    // macOS and Linux (LP64: C `long` is 64-bit) and throws ClassCastException on win32-x64
    // (LLP64: C `long` is 32-bit, so the canonical layout is OfInt). The throw happens in this
    // class's STATIC INITIALIZER, so on Windows every single binding in com.periut.webgpu was
    // dead on arrival -- WebGPUContext.create() failed with ExceptionInInitializerError before
    // reaching a single native call, and GpuBackend reported "no WebGPU device: unavailable",
    // which reads like a missing driver rather than a layout cast.
    //
    // Widening to `long long` on such platforms is correct rather than merely convenient: these
    // bindings were generated from macOS headers where `size_t`, `intptr_t` and `ptrdiff_t` are
    // `long`, and every one of C_LONG's ~115 uses is one of those (the size_t `*Count` and
    // `length` struct fields, and the size_t offset/size/count parameters of
    // wgpuQueueWriteBuffer, wgpuBufferMapAsync, wgpuRenderPassEncoderSetBindGroup and friends).
    // All of them are 64-bit on win32-x64 too. webgpu.h itself declares no `long` field, so
    // nothing here wants the platform's real 32-bit `long`.
    public static final ValueLayout.OfLong C_LONG = cLong();

    private static ValueLayout.OfLong cLong() {
        MemoryLayout canonical = Linker.nativeLinker().canonicalLayouts().get("long");
        if (canonical instanceof ValueLayout.OfLong ofLong) {
            return ofLong;
        }
        return (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long long");
    }

    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }
}

