// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUDawnWGSLBlocklist {
 *     WGPUChainedStruct chain;
 *     size_t blocklistedFeatureCount;
 *     const char *const *blocklistedFeatures;
 * }
 * }
 */
public class WGPUDawnWGSLBlocklist {

    WGPUDawnWGSLBlocklist() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG.withName("blocklistedFeatureCount"),
        webgpu_h.C_POINTER.withName("blocklistedFeatures")
    ).withName("WGPUDawnWGSLBlocklist");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong blocklistedFeatureCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("blocklistedFeatureCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t blocklistedFeatureCount
     * }
     */
    public static final OfLong blocklistedFeatureCount$layout() {
        return blocklistedFeatureCount$LAYOUT;
    }

    private static final long blocklistedFeatureCount$OFFSET = $LAYOUT.byteOffset(groupElement("blocklistedFeatureCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t blocklistedFeatureCount
     * }
     */
    public static final long blocklistedFeatureCount$offset() {
        return blocklistedFeatureCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t blocklistedFeatureCount
     * }
     */
    public static long blocklistedFeatureCount(MemorySegment struct) {
        return struct.get(blocklistedFeatureCount$LAYOUT, blocklistedFeatureCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t blocklistedFeatureCount
     * }
     */
    public static void blocklistedFeatureCount(MemorySegment struct, long fieldValue) {
        struct.set(blocklistedFeatureCount$LAYOUT, blocklistedFeatureCount$OFFSET, fieldValue);
    }

    private static final AddressLayout blocklistedFeatures$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("blocklistedFeatures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *const *blocklistedFeatures
     * }
     */
    public static final AddressLayout blocklistedFeatures$layout() {
        return blocklistedFeatures$LAYOUT;
    }

    private static final long blocklistedFeatures$OFFSET = $LAYOUT.byteOffset(groupElement("blocklistedFeatures"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *const *blocklistedFeatures
     * }
     */
    public static final long blocklistedFeatures$offset() {
        return blocklistedFeatures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *const *blocklistedFeatures
     * }
     */
    public static MemorySegment blocklistedFeatures(MemorySegment struct) {
        return struct.get(blocklistedFeatures$LAYOUT, blocklistedFeatures$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *const *blocklistedFeatures
     * }
     */
    public static void blocklistedFeatures(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(blocklistedFeatures$LAYOUT, blocklistedFeatures$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

