// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUCompilationMessage {
 *     WGPUChainedStruct *nextInChain;
 *     WGPUStringView message;
 *     WGPUCompilationMessageType type;
 *     uint64_t lineNum;
 *     uint64_t linePos;
 *     uint64_t offset;
 *     uint64_t length;
 * }
 * }
 */
public class WGPUCompilationMessage {

    WGPUCompilationMessage() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        WGPUStringView.layout().withName("message"),
        webgpu_h.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_LONG_LONG.withName("lineNum"),
        webgpu_h.C_LONG_LONG.withName("linePos"),
        webgpu_h.C_LONG_LONG.withName("offset"),
        webgpu_h.C_LONG_LONG.withName("length")
    ).withName("WGPUCompilationMessage");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final GroupLayout message$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUStringView message
     * }
     */
    public static final GroupLayout message$layout() {
        return message$LAYOUT;
    }

    private static final long message$OFFSET = $LAYOUT.byteOffset(groupElement("message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUStringView message
     * }
     */
    public static final long message$offset() {
        return message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUStringView message
     * }
     */
    public static MemorySegment message(MemorySegment struct) {
        return struct.asSlice(message$OFFSET, message$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUStringView message
     * }
     */
    public static void message(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, message$OFFSET, message$LAYOUT.byteSize());
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUCompilationMessageType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUCompilationMessageType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUCompilationMessageType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUCompilationMessageType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfLong lineNum$LAYOUT = (OfLong)$LAYOUT.select(groupElement("lineNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t lineNum
     * }
     */
    public static final OfLong lineNum$layout() {
        return lineNum$LAYOUT;
    }

    private static final long lineNum$OFFSET = $LAYOUT.byteOffset(groupElement("lineNum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t lineNum
     * }
     */
    public static final long lineNum$offset() {
        return lineNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t lineNum
     * }
     */
    public static long lineNum(MemorySegment struct) {
        return struct.get(lineNum$LAYOUT, lineNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t lineNum
     * }
     */
    public static void lineNum(MemorySegment struct, long fieldValue) {
        struct.set(lineNum$LAYOUT, lineNum$OFFSET, fieldValue);
    }

    private static final OfLong linePos$LAYOUT = (OfLong)$LAYOUT.select(groupElement("linePos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t linePos
     * }
     */
    public static final OfLong linePos$layout() {
        return linePos$LAYOUT;
    }

    private static final long linePos$OFFSET = $LAYOUT.byteOffset(groupElement("linePos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t linePos
     * }
     */
    public static final long linePos$offset() {
        return linePos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t linePos
     * }
     */
    public static long linePos(MemorySegment struct) {
        return struct.get(linePos$LAYOUT, linePos$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t linePos
     * }
     */
    public static void linePos(MemorySegment struct, long fieldValue) {
        struct.set(linePos$LAYOUT, linePos$OFFSET, fieldValue);
    }

    private static final OfLong offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final OfLong offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static long offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static void offset(MemorySegment struct, long fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    private static final OfLong length$LAYOUT = (OfLong)$LAYOUT.select(groupElement("length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t length
     * }
     */
    public static final OfLong length$layout() {
        return length$LAYOUT;
    }

    private static final long length$OFFSET = $LAYOUT.byteOffset(groupElement("length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t length
     * }
     */
    public static final long length$offset() {
        return length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t length
     * }
     */
    public static long length(MemorySegment struct) {
        return struct.get(length$LAYOUT, length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t length
     * }
     */
    public static void length(MemorySegment struct, long fieldValue) {
        struct.set(length$LAYOUT, length$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

