// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUDawnDrmFormatCapabilities {
 *     WGPUChainedStruct chain;
 *     size_t propertiesCount;
 *     const WGPUDawnDrmFormatProperties *properties;
 * }
 * }
 */
public class WGPUDawnDrmFormatCapabilities {

    WGPUDawnDrmFormatCapabilities() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG.withName("propertiesCount"),
        webgpu_h.C_POINTER.withName("properties")
    ).withName("WGPUDawnDrmFormatCapabilities");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong propertiesCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("propertiesCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t propertiesCount
     * }
     */
    public static final OfLong propertiesCount$layout() {
        return propertiesCount$LAYOUT;
    }

    private static final long propertiesCount$OFFSET = $LAYOUT.byteOffset(groupElement("propertiesCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t propertiesCount
     * }
     */
    public static final long propertiesCount$offset() {
        return propertiesCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t propertiesCount
     * }
     */
    public static long propertiesCount(MemorySegment struct) {
        return struct.get(propertiesCount$LAYOUT, propertiesCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t propertiesCount
     * }
     */
    public static void propertiesCount(MemorySegment struct, long fieldValue) {
        struct.set(propertiesCount$LAYOUT, propertiesCount$OFFSET, fieldValue);
    }

    private static final AddressLayout properties$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("properties"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUDawnDrmFormatProperties *properties
     * }
     */
    public static final AddressLayout properties$layout() {
        return properties$LAYOUT;
    }

    private static final long properties$OFFSET = $LAYOUT.byteOffset(groupElement("properties"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUDawnDrmFormatProperties *properties
     * }
     */
    public static final long properties$offset() {
        return properties$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUDawnDrmFormatProperties *properties
     * }
     */
    public static MemorySegment properties(MemorySegment struct) {
        return struct.get(properties$LAYOUT, properties$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUDawnDrmFormatProperties *properties
     * }
     */
    public static void properties(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(properties$LAYOUT, properties$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

