// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUSharedTextureMemoryDmaBufDescriptor {
 *     WGPUChainedStruct chain;
 *     WGPUExtent3D size;
 *     uint32_t drmFormat;
 *     uint64_t drmModifier;
 *     size_t planeCount;
 *     const WGPUSharedTextureMemoryDmaBufPlane *planes;
 * }
 * }
 */
public class WGPUSharedTextureMemoryDmaBufDescriptor {

    WGPUSharedTextureMemoryDmaBufDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        WGPUExtent3D.layout().withName("size"),
        webgpu_h.C_INT.withName("drmFormat"),
        webgpu_h.C_LONG_LONG.withName("drmModifier"),
        webgpu_h.C_LONG.withName("planeCount"),
        webgpu_h.C_POINTER.withName("planes")
    ).withName("WGPUSharedTextureMemoryDmaBufDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final GroupLayout size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUExtent3D size
     * }
     */
    public static final GroupLayout size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUExtent3D size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUExtent3D size
     * }
     */
    public static MemorySegment size(MemorySegment struct) {
        return struct.asSlice(size$OFFSET, size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUExtent3D size
     * }
     */
    public static void size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, size$OFFSET, size$LAYOUT.byteSize());
    }

    private static final OfInt drmFormat$LAYOUT = (OfInt)$LAYOUT.select(groupElement("drmFormat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t drmFormat
     * }
     */
    public static final OfInt drmFormat$layout() {
        return drmFormat$LAYOUT;
    }

    private static final long drmFormat$OFFSET = $LAYOUT.byteOffset(groupElement("drmFormat"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t drmFormat
     * }
     */
    public static final long drmFormat$offset() {
        return drmFormat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t drmFormat
     * }
     */
    public static int drmFormat(MemorySegment struct) {
        return struct.get(drmFormat$LAYOUT, drmFormat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t drmFormat
     * }
     */
    public static void drmFormat(MemorySegment struct, int fieldValue) {
        struct.set(drmFormat$LAYOUT, drmFormat$OFFSET, fieldValue);
    }

    private static final OfLong drmModifier$LAYOUT = (OfLong)$LAYOUT.select(groupElement("drmModifier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t drmModifier
     * }
     */
    public static final OfLong drmModifier$layout() {
        return drmModifier$LAYOUT;
    }

    private static final long drmModifier$OFFSET = $LAYOUT.byteOffset(groupElement("drmModifier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t drmModifier
     * }
     */
    public static final long drmModifier$offset() {
        return drmModifier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t drmModifier
     * }
     */
    public static long drmModifier(MemorySegment struct) {
        return struct.get(drmModifier$LAYOUT, drmModifier$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t drmModifier
     * }
     */
    public static void drmModifier(MemorySegment struct, long fieldValue) {
        struct.set(drmModifier$LAYOUT, drmModifier$OFFSET, fieldValue);
    }

    private static final OfLong planeCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("planeCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t planeCount
     * }
     */
    public static final OfLong planeCount$layout() {
        return planeCount$LAYOUT;
    }

    private static final long planeCount$OFFSET = $LAYOUT.byteOffset(groupElement("planeCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t planeCount
     * }
     */
    public static final long planeCount$offset() {
        return planeCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t planeCount
     * }
     */
    public static long planeCount(MemorySegment struct) {
        return struct.get(planeCount$LAYOUT, planeCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t planeCount
     * }
     */
    public static void planeCount(MemorySegment struct, long fieldValue) {
        struct.set(planeCount$LAYOUT, planeCount$OFFSET, fieldValue);
    }

    private static final AddressLayout planes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("planes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUSharedTextureMemoryDmaBufPlane *planes
     * }
     */
    public static final AddressLayout planes$layout() {
        return planes$LAYOUT;
    }

    private static final long planes$OFFSET = $LAYOUT.byteOffset(groupElement("planes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUSharedTextureMemoryDmaBufPlane *planes
     * }
     */
    public static final long planes$offset() {
        return planes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUSharedTextureMemoryDmaBufPlane *planes
     * }
     */
    public static MemorySegment planes(MemorySegment struct) {
        return struct.get(planes$LAYOUT, planes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUSharedTextureMemoryDmaBufPlane *planes
     * }
     */
    public static void planes(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(planes$LAYOUT, planes$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

