// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPURenderPassStorageAttachment {
 *     WGPUChainedStruct *nextInChain;
 *     uint64_t offset;
 *     WGPUTextureView storage;
 *     WGPULoadOp loadOp;
 *     WGPUStoreOp storeOp;
 *     WGPUColor clearValue;
 * }
 * }
 */
public class WGPURenderPassStorageAttachment {

    WGPURenderPassStorageAttachment() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        webgpu_h.C_LONG_LONG.withName("offset"),
        webgpu_h.C_POINTER.withName("storage"),
        webgpu_h.C_INT.withName("loadOp"),
        webgpu_h.C_INT.withName("storeOp"),
        WGPUColor.layout().withName("clearValue")
    ).withName("WGPURenderPassStorageAttachment");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final OfLong offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final OfLong offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static long offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static void offset(MemorySegment struct, long fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    private static final AddressLayout storage$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("storage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUTextureView storage
     * }
     */
    public static final AddressLayout storage$layout() {
        return storage$LAYOUT;
    }

    private static final long storage$OFFSET = $LAYOUT.byteOffset(groupElement("storage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUTextureView storage
     * }
     */
    public static final long storage$offset() {
        return storage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUTextureView storage
     * }
     */
    public static MemorySegment storage(MemorySegment struct) {
        return struct.get(storage$LAYOUT, storage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUTextureView storage
     * }
     */
    public static void storage(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(storage$LAYOUT, storage$OFFSET, fieldValue);
    }

    private static final OfInt loadOp$LAYOUT = (OfInt)$LAYOUT.select(groupElement("loadOp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPULoadOp loadOp
     * }
     */
    public static final OfInt loadOp$layout() {
        return loadOp$LAYOUT;
    }

    private static final long loadOp$OFFSET = $LAYOUT.byteOffset(groupElement("loadOp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPULoadOp loadOp
     * }
     */
    public static final long loadOp$offset() {
        return loadOp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPULoadOp loadOp
     * }
     */
    public static int loadOp(MemorySegment struct) {
        return struct.get(loadOp$LAYOUT, loadOp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPULoadOp loadOp
     * }
     */
    public static void loadOp(MemorySegment struct, int fieldValue) {
        struct.set(loadOp$LAYOUT, loadOp$OFFSET, fieldValue);
    }

    private static final OfInt storeOp$LAYOUT = (OfInt)$LAYOUT.select(groupElement("storeOp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUStoreOp storeOp
     * }
     */
    public static final OfInt storeOp$layout() {
        return storeOp$LAYOUT;
    }

    private static final long storeOp$OFFSET = $LAYOUT.byteOffset(groupElement("storeOp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUStoreOp storeOp
     * }
     */
    public static final long storeOp$offset() {
        return storeOp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUStoreOp storeOp
     * }
     */
    public static int storeOp(MemorySegment struct) {
        return struct.get(storeOp$LAYOUT, storeOp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUStoreOp storeOp
     * }
     */
    public static void storeOp(MemorySegment struct, int fieldValue) {
        struct.set(storeOp$LAYOUT, storeOp$OFFSET, fieldValue);
    }

    private static final GroupLayout clearValue$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("clearValue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUColor clearValue
     * }
     */
    public static final GroupLayout clearValue$layout() {
        return clearValue$LAYOUT;
    }

    private static final long clearValue$OFFSET = $LAYOUT.byteOffset(groupElement("clearValue"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUColor clearValue
     * }
     */
    public static final long clearValue$offset() {
        return clearValue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUColor clearValue
     * }
     */
    public static MemorySegment clearValue(MemorySegment struct) {
        return struct.asSlice(clearValue$OFFSET, clearValue$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUColor clearValue
     * }
     */
    public static void clearValue(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, clearValue$OFFSET, clearValue$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

