// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef WGPUFuture (*WGPUProcInstanceRequestAdapter)(WGPUInstance, const WGPURequestAdapterOptions *, WGPURequestAdapterCallbackInfo)
 * }
 */
public final class WGPUProcInstanceRequestAdapter {

    private WGPUProcInstanceRequestAdapter() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment instance, MemorySegment options, MemorySegment callbackInfo);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        WGPUFuture.layout(),
        webgpu_h.C_POINTER,
        webgpu_h.C_POINTER,
        WGPURequestAdapterCallbackInfo.layout()
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = webgpu_h.upcallHandle(WGPUProcInstanceRequestAdapter.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(WGPUProcInstanceRequestAdapter.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr, SegmentAllocator alloc, MemorySegment instance, MemorySegment options, MemorySegment callbackInfo) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, alloc, instance, options, callbackInfo);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

