// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUSharedBufferMemoryBeginAccessDescriptor {
 *     WGPUChainedStruct *nextInChain;
 *     WGPUBool initialized;
 *     size_t fenceCount;
 *     const WGPUSharedFence *fences;
 *     const uint64_t *signaledValues;
 * }
 * }
 */
public class WGPUSharedBufferMemoryBeginAccessDescriptor {

    WGPUSharedBufferMemoryBeginAccessDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        webgpu_h.C_INT.withName("initialized"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_LONG.withName("fenceCount"),
        webgpu_h.C_POINTER.withName("fences"),
        webgpu_h.C_POINTER.withName("signaledValues")
    ).withName("WGPUSharedBufferMemoryBeginAccessDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final OfInt initialized$LAYOUT = (OfInt)$LAYOUT.select(groupElement("initialized"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool initialized
     * }
     */
    public static final OfInt initialized$layout() {
        return initialized$LAYOUT;
    }

    private static final long initialized$OFFSET = $LAYOUT.byteOffset(groupElement("initialized"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool initialized
     * }
     */
    public static final long initialized$offset() {
        return initialized$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool initialized
     * }
     */
    public static int initialized(MemorySegment struct) {
        return struct.get(initialized$LAYOUT, initialized$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool initialized
     * }
     */
    public static void initialized(MemorySegment struct, int fieldValue) {
        struct.set(initialized$LAYOUT, initialized$OFFSET, fieldValue);
    }

    private static final OfLong fenceCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("fenceCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t fenceCount
     * }
     */
    public static final OfLong fenceCount$layout() {
        return fenceCount$LAYOUT;
    }

    private static final long fenceCount$OFFSET = $LAYOUT.byteOffset(groupElement("fenceCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t fenceCount
     * }
     */
    public static final long fenceCount$offset() {
        return fenceCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t fenceCount
     * }
     */
    public static long fenceCount(MemorySegment struct) {
        return struct.get(fenceCount$LAYOUT, fenceCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t fenceCount
     * }
     */
    public static void fenceCount(MemorySegment struct, long fieldValue) {
        struct.set(fenceCount$LAYOUT, fenceCount$OFFSET, fieldValue);
    }

    private static final AddressLayout fences$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fences"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUSharedFence *fences
     * }
     */
    public static final AddressLayout fences$layout() {
        return fences$LAYOUT;
    }

    private static final long fences$OFFSET = $LAYOUT.byteOffset(groupElement("fences"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUSharedFence *fences
     * }
     */
    public static final long fences$offset() {
        return fences$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUSharedFence *fences
     * }
     */
    public static MemorySegment fences(MemorySegment struct) {
        return struct.get(fences$LAYOUT, fences$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUSharedFence *fences
     * }
     */
    public static void fences(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fences$LAYOUT, fences$OFFSET, fieldValue);
    }

    private static final AddressLayout signaledValues$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("signaledValues"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint64_t *signaledValues
     * }
     */
    public static final AddressLayout signaledValues$layout() {
        return signaledValues$LAYOUT;
    }

    private static final long signaledValues$OFFSET = $LAYOUT.byteOffset(groupElement("signaledValues"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint64_t *signaledValues
     * }
     */
    public static final long signaledValues$offset() {
        return signaledValues$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint64_t *signaledValues
     * }
     */
    public static MemorySegment signaledValues(MemorySegment struct) {
        return struct.get(signaledValues$LAYOUT, signaledValues$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint64_t *signaledValues
     * }
     */
    public static void signaledValues(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(signaledValues$LAYOUT, signaledValues$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

