// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUDawnFakeBufferOOMForTesting {
 *     WGPUChainedStruct chain;
 *     WGPUBool fakeOOMAtWireClientMap;
 *     WGPUBool fakeOOMAtNativeMap;
 *     WGPUBool fakeOOMAtDevice;
 * }
 * }
 */
public class WGPUDawnFakeBufferOOMForTesting {

    WGPUDawnFakeBufferOOMForTesting() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("fakeOOMAtWireClientMap"),
        webgpu_h.C_INT.withName("fakeOOMAtNativeMap"),
        webgpu_h.C_INT.withName("fakeOOMAtDevice"),
        MemoryLayout.paddingLayout(4)
    ).withName("WGPUDawnFakeBufferOOMForTesting");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt fakeOOMAtWireClientMap$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fakeOOMAtWireClientMap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtWireClientMap
     * }
     */
    public static final OfInt fakeOOMAtWireClientMap$layout() {
        return fakeOOMAtWireClientMap$LAYOUT;
    }

    private static final long fakeOOMAtWireClientMap$OFFSET = $LAYOUT.byteOffset(groupElement("fakeOOMAtWireClientMap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtWireClientMap
     * }
     */
    public static final long fakeOOMAtWireClientMap$offset() {
        return fakeOOMAtWireClientMap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtWireClientMap
     * }
     */
    public static int fakeOOMAtWireClientMap(MemorySegment struct) {
        return struct.get(fakeOOMAtWireClientMap$LAYOUT, fakeOOMAtWireClientMap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtWireClientMap
     * }
     */
    public static void fakeOOMAtWireClientMap(MemorySegment struct, int fieldValue) {
        struct.set(fakeOOMAtWireClientMap$LAYOUT, fakeOOMAtWireClientMap$OFFSET, fieldValue);
    }

    private static final OfInt fakeOOMAtNativeMap$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fakeOOMAtNativeMap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtNativeMap
     * }
     */
    public static final OfInt fakeOOMAtNativeMap$layout() {
        return fakeOOMAtNativeMap$LAYOUT;
    }

    private static final long fakeOOMAtNativeMap$OFFSET = $LAYOUT.byteOffset(groupElement("fakeOOMAtNativeMap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtNativeMap
     * }
     */
    public static final long fakeOOMAtNativeMap$offset() {
        return fakeOOMAtNativeMap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtNativeMap
     * }
     */
    public static int fakeOOMAtNativeMap(MemorySegment struct) {
        return struct.get(fakeOOMAtNativeMap$LAYOUT, fakeOOMAtNativeMap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtNativeMap
     * }
     */
    public static void fakeOOMAtNativeMap(MemorySegment struct, int fieldValue) {
        struct.set(fakeOOMAtNativeMap$LAYOUT, fakeOOMAtNativeMap$OFFSET, fieldValue);
    }

    private static final OfInt fakeOOMAtDevice$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fakeOOMAtDevice"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtDevice
     * }
     */
    public static final OfInt fakeOOMAtDevice$layout() {
        return fakeOOMAtDevice$LAYOUT;
    }

    private static final long fakeOOMAtDevice$OFFSET = $LAYOUT.byteOffset(groupElement("fakeOOMAtDevice"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtDevice
     * }
     */
    public static final long fakeOOMAtDevice$offset() {
        return fakeOOMAtDevice$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtDevice
     * }
     */
    public static int fakeOOMAtDevice(MemorySegment struct) {
        return struct.get(fakeOOMAtDevice$LAYOUT, fakeOOMAtDevice$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool fakeOOMAtDevice
     * }
     */
    public static void fakeOOMAtDevice(MemorySegment struct, int fieldValue) {
        struct.set(fakeOOMAtDevice$LAYOUT, fakeOOMAtDevice$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

