// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUDawnCacheDeviceDescriptor {
 *     WGPUChainedStruct chain;
 *     WGPUStringView isolationKey;
 *     WGPUDawnLoadCacheDataFunction loadDataFunction;
 *     WGPUDawnStoreCacheDataFunction storeDataFunction;
 *     void *functionUserdata;
 * }
 * }
 */
public class WGPUDawnCacheDeviceDescriptor {

    WGPUDawnCacheDeviceDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        WGPUStringView.layout().withName("isolationKey"),
        webgpu_h.C_POINTER.withName("loadDataFunction"),
        webgpu_h.C_POINTER.withName("storeDataFunction"),
        webgpu_h.C_POINTER.withName("functionUserdata")
    ).withName("WGPUDawnCacheDeviceDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final GroupLayout isolationKey$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("isolationKey"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUStringView isolationKey
     * }
     */
    public static final GroupLayout isolationKey$layout() {
        return isolationKey$LAYOUT;
    }

    private static final long isolationKey$OFFSET = $LAYOUT.byteOffset(groupElement("isolationKey"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUStringView isolationKey
     * }
     */
    public static final long isolationKey$offset() {
        return isolationKey$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUStringView isolationKey
     * }
     */
    public static MemorySegment isolationKey(MemorySegment struct) {
        return struct.asSlice(isolationKey$OFFSET, isolationKey$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUStringView isolationKey
     * }
     */
    public static void isolationKey(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, isolationKey$OFFSET, isolationKey$LAYOUT.byteSize());
    }

    private static final AddressLayout loadDataFunction$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("loadDataFunction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUDawnLoadCacheDataFunction loadDataFunction
     * }
     */
    public static final AddressLayout loadDataFunction$layout() {
        return loadDataFunction$LAYOUT;
    }

    private static final long loadDataFunction$OFFSET = $LAYOUT.byteOffset(groupElement("loadDataFunction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUDawnLoadCacheDataFunction loadDataFunction
     * }
     */
    public static final long loadDataFunction$offset() {
        return loadDataFunction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUDawnLoadCacheDataFunction loadDataFunction
     * }
     */
    public static MemorySegment loadDataFunction(MemorySegment struct) {
        return struct.get(loadDataFunction$LAYOUT, loadDataFunction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUDawnLoadCacheDataFunction loadDataFunction
     * }
     */
    public static void loadDataFunction(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(loadDataFunction$LAYOUT, loadDataFunction$OFFSET, fieldValue);
    }

    private static final AddressLayout storeDataFunction$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("storeDataFunction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUDawnStoreCacheDataFunction storeDataFunction
     * }
     */
    public static final AddressLayout storeDataFunction$layout() {
        return storeDataFunction$LAYOUT;
    }

    private static final long storeDataFunction$OFFSET = $LAYOUT.byteOffset(groupElement("storeDataFunction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUDawnStoreCacheDataFunction storeDataFunction
     * }
     */
    public static final long storeDataFunction$offset() {
        return storeDataFunction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUDawnStoreCacheDataFunction storeDataFunction
     * }
     */
    public static MemorySegment storeDataFunction(MemorySegment struct) {
        return struct.get(storeDataFunction$LAYOUT, storeDataFunction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUDawnStoreCacheDataFunction storeDataFunction
     * }
     */
    public static void storeDataFunction(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(storeDataFunction$LAYOUT, storeDataFunction$OFFSET, fieldValue);
    }

    private static final AddressLayout functionUserdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("functionUserdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *functionUserdata
     * }
     */
    public static final AddressLayout functionUserdata$layout() {
        return functionUserdata$LAYOUT;
    }

    private static final long functionUserdata$OFFSET = $LAYOUT.byteOffset(groupElement("functionUserdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *functionUserdata
     * }
     */
    public static final long functionUserdata$offset() {
        return functionUserdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *functionUserdata
     * }
     */
    public static MemorySegment functionUserdata(MemorySegment struct) {
        return struct.get(functionUserdata$LAYOUT, functionUserdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *functionUserdata
     * }
     */
    public static void functionUserdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(functionUserdata$LAYOUT, functionUserdata$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

