// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUDawnTogglesDescriptor {
 *     WGPUChainedStruct chain;
 *     size_t enabledToggleCount;
 *     const char *const *enabledToggles;
 *     size_t disabledToggleCount;
 *     const char *const *disabledToggles;
 * }
 * }
 */
public class WGPUDawnTogglesDescriptor {

    WGPUDawnTogglesDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG.withName("enabledToggleCount"),
        webgpu_h.C_POINTER.withName("enabledToggles"),
        webgpu_h.C_LONG.withName("disabledToggleCount"),
        webgpu_h.C_POINTER.withName("disabledToggles")
    ).withName("WGPUDawnTogglesDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong enabledToggleCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("enabledToggleCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t enabledToggleCount
     * }
     */
    public static final OfLong enabledToggleCount$layout() {
        return enabledToggleCount$LAYOUT;
    }

    private static final long enabledToggleCount$OFFSET = $LAYOUT.byteOffset(groupElement("enabledToggleCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t enabledToggleCount
     * }
     */
    public static final long enabledToggleCount$offset() {
        return enabledToggleCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t enabledToggleCount
     * }
     */
    public static long enabledToggleCount(MemorySegment struct) {
        return struct.get(enabledToggleCount$LAYOUT, enabledToggleCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t enabledToggleCount
     * }
     */
    public static void enabledToggleCount(MemorySegment struct, long fieldValue) {
        struct.set(enabledToggleCount$LAYOUT, enabledToggleCount$OFFSET, fieldValue);
    }

    private static final AddressLayout enabledToggles$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("enabledToggles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *const *enabledToggles
     * }
     */
    public static final AddressLayout enabledToggles$layout() {
        return enabledToggles$LAYOUT;
    }

    private static final long enabledToggles$OFFSET = $LAYOUT.byteOffset(groupElement("enabledToggles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *const *enabledToggles
     * }
     */
    public static final long enabledToggles$offset() {
        return enabledToggles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *const *enabledToggles
     * }
     */
    public static MemorySegment enabledToggles(MemorySegment struct) {
        return struct.get(enabledToggles$LAYOUT, enabledToggles$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *const *enabledToggles
     * }
     */
    public static void enabledToggles(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(enabledToggles$LAYOUT, enabledToggles$OFFSET, fieldValue);
    }

    private static final OfLong disabledToggleCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("disabledToggleCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t disabledToggleCount
     * }
     */
    public static final OfLong disabledToggleCount$layout() {
        return disabledToggleCount$LAYOUT;
    }

    private static final long disabledToggleCount$OFFSET = $LAYOUT.byteOffset(groupElement("disabledToggleCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t disabledToggleCount
     * }
     */
    public static final long disabledToggleCount$offset() {
        return disabledToggleCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t disabledToggleCount
     * }
     */
    public static long disabledToggleCount(MemorySegment struct) {
        return struct.get(disabledToggleCount$LAYOUT, disabledToggleCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t disabledToggleCount
     * }
     */
    public static void disabledToggleCount(MemorySegment struct, long fieldValue) {
        struct.set(disabledToggleCount$LAYOUT, disabledToggleCount$OFFSET, fieldValue);
    }

    private static final AddressLayout disabledToggles$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("disabledToggles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *const *disabledToggles
     * }
     */
    public static final AddressLayout disabledToggles$layout() {
        return disabledToggles$LAYOUT;
    }

    private static final long disabledToggles$OFFSET = $LAYOUT.byteOffset(groupElement("disabledToggles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *const *disabledToggles
     * }
     */
    public static final long disabledToggles$offset() {
        return disabledToggles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *const *disabledToggles
     * }
     */
    public static MemorySegment disabledToggles(MemorySegment struct) {
        return struct.get(disabledToggles$LAYOUT, disabledToggles$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *const *disabledToggles
     * }
     */
    public static void disabledToggles(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(disabledToggles$LAYOUT, disabledToggles$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

