// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUInstanceDescriptor {
 *     WGPUChainedStruct *nextInChain;
 *     size_t requiredFeatureCount;
 *     const WGPUInstanceFeatureName *requiredFeatures;
 *     const WGPUInstanceLimits *requiredLimits;
 * }
 * }
 */
public class WGPUInstanceDescriptor {

    WGPUInstanceDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        webgpu_h.C_LONG.withName("requiredFeatureCount"),
        webgpu_h.C_POINTER.withName("requiredFeatures"),
        webgpu_h.C_POINTER.withName("requiredLimits")
    ).withName("WGPUInstanceDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final OfLong requiredFeatureCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("requiredFeatureCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t requiredFeatureCount
     * }
     */
    public static final OfLong requiredFeatureCount$layout() {
        return requiredFeatureCount$LAYOUT;
    }

    private static final long requiredFeatureCount$OFFSET = $LAYOUT.byteOffset(groupElement("requiredFeatureCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t requiredFeatureCount
     * }
     */
    public static final long requiredFeatureCount$offset() {
        return requiredFeatureCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t requiredFeatureCount
     * }
     */
    public static long requiredFeatureCount(MemorySegment struct) {
        return struct.get(requiredFeatureCount$LAYOUT, requiredFeatureCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t requiredFeatureCount
     * }
     */
    public static void requiredFeatureCount(MemorySegment struct, long fieldValue) {
        struct.set(requiredFeatureCount$LAYOUT, requiredFeatureCount$OFFSET, fieldValue);
    }

    private static final AddressLayout requiredFeatures$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("requiredFeatures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUInstanceFeatureName *requiredFeatures
     * }
     */
    public static final AddressLayout requiredFeatures$layout() {
        return requiredFeatures$LAYOUT;
    }

    private static final long requiredFeatures$OFFSET = $LAYOUT.byteOffset(groupElement("requiredFeatures"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUInstanceFeatureName *requiredFeatures
     * }
     */
    public static final long requiredFeatures$offset() {
        return requiredFeatures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUInstanceFeatureName *requiredFeatures
     * }
     */
    public static MemorySegment requiredFeatures(MemorySegment struct) {
        return struct.get(requiredFeatures$LAYOUT, requiredFeatures$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUInstanceFeatureName *requiredFeatures
     * }
     */
    public static void requiredFeatures(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(requiredFeatures$LAYOUT, requiredFeatures$OFFSET, fieldValue);
    }

    private static final AddressLayout requiredLimits$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("requiredLimits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUInstanceLimits *requiredLimits
     * }
     */
    public static final AddressLayout requiredLimits$layout() {
        return requiredLimits$LAYOUT;
    }

    private static final long requiredLimits$OFFSET = $LAYOUT.byteOffset(groupElement("requiredLimits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUInstanceLimits *requiredLimits
     * }
     */
    public static final long requiredLimits$offset() {
        return requiredLimits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUInstanceLimits *requiredLimits
     * }
     */
    public static MemorySegment requiredLimits(MemorySegment struct) {
        return struct.get(requiredLimits$LAYOUT, requiredLimits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUInstanceLimits *requiredLimits
     * }
     */
    public static void requiredLimits(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(requiredLimits$LAYOUT, requiredLimits$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

