// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUSharedTextureMemoryVkImageLayoutEndState {
 *     WGPUChainedStruct chain;
 *     int32_t oldLayout;
 *     int32_t newLayout;
 * }
 * }
 */
public class WGPUSharedTextureMemoryVkImageLayoutEndState {

    WGPUSharedTextureMemoryVkImageLayoutEndState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("oldLayout"),
        webgpu_h.C_INT.withName("newLayout")
    ).withName("WGPUSharedTextureMemoryVkImageLayoutEndState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt oldLayout$LAYOUT = (OfInt)$LAYOUT.select(groupElement("oldLayout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t oldLayout
     * }
     */
    public static final OfInt oldLayout$layout() {
        return oldLayout$LAYOUT;
    }

    private static final long oldLayout$OFFSET = $LAYOUT.byteOffset(groupElement("oldLayout"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t oldLayout
     * }
     */
    public static final long oldLayout$offset() {
        return oldLayout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t oldLayout
     * }
     */
    public static int oldLayout(MemorySegment struct) {
        return struct.get(oldLayout$LAYOUT, oldLayout$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t oldLayout
     * }
     */
    public static void oldLayout(MemorySegment struct, int fieldValue) {
        struct.set(oldLayout$LAYOUT, oldLayout$OFFSET, fieldValue);
    }

    private static final OfInt newLayout$LAYOUT = (OfInt)$LAYOUT.select(groupElement("newLayout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t newLayout
     * }
     */
    public static final OfInt newLayout$layout() {
        return newLayout$LAYOUT;
    }

    private static final long newLayout$OFFSET = $LAYOUT.byteOffset(groupElement("newLayout"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t newLayout
     * }
     */
    public static final long newLayout$offset() {
        return newLayout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t newLayout
     * }
     */
    public static int newLayout(MemorySegment struct) {
        return struct.get(newLayout$LAYOUT, newLayout$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t newLayout
     * }
     */
    public static void newLayout(MemorySegment struct, int fieldValue) {
        struct.set(newLayout$LAYOUT, newLayout$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

