// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPURenderPassDescriptorResolveRect {
 *     WGPUChainedStruct chain;
 *     uint32_t colorOffsetX;
 *     uint32_t colorOffsetY;
 *     uint32_t resolveOffsetX;
 *     uint32_t resolveOffsetY;
 *     uint32_t width;
 *     uint32_t height;
 * }
 * }
 */
public class WGPURenderPassDescriptorResolveRect {

    WGPURenderPassDescriptorResolveRect() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("colorOffsetX"),
        webgpu_h.C_INT.withName("colorOffsetY"),
        webgpu_h.C_INT.withName("resolveOffsetX"),
        webgpu_h.C_INT.withName("resolveOffsetY"),
        webgpu_h.C_INT.withName("width"),
        webgpu_h.C_INT.withName("height")
    ).withName("WGPURenderPassDescriptorResolveRect");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt colorOffsetX$LAYOUT = (OfInt)$LAYOUT.select(groupElement("colorOffsetX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetX
     * }
     */
    public static final OfInt colorOffsetX$layout() {
        return colorOffsetX$LAYOUT;
    }

    private static final long colorOffsetX$OFFSET = $LAYOUT.byteOffset(groupElement("colorOffsetX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetX
     * }
     */
    public static final long colorOffsetX$offset() {
        return colorOffsetX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetX
     * }
     */
    public static int colorOffsetX(MemorySegment struct) {
        return struct.get(colorOffsetX$LAYOUT, colorOffsetX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetX
     * }
     */
    public static void colorOffsetX(MemorySegment struct, int fieldValue) {
        struct.set(colorOffsetX$LAYOUT, colorOffsetX$OFFSET, fieldValue);
    }

    private static final OfInt colorOffsetY$LAYOUT = (OfInt)$LAYOUT.select(groupElement("colorOffsetY"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetY
     * }
     */
    public static final OfInt colorOffsetY$layout() {
        return colorOffsetY$LAYOUT;
    }

    private static final long colorOffsetY$OFFSET = $LAYOUT.byteOffset(groupElement("colorOffsetY"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetY
     * }
     */
    public static final long colorOffsetY$offset() {
        return colorOffsetY$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetY
     * }
     */
    public static int colorOffsetY(MemorySegment struct) {
        return struct.get(colorOffsetY$LAYOUT, colorOffsetY$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t colorOffsetY
     * }
     */
    public static void colorOffsetY(MemorySegment struct, int fieldValue) {
        struct.set(colorOffsetY$LAYOUT, colorOffsetY$OFFSET, fieldValue);
    }

    private static final OfInt resolveOffsetX$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resolveOffsetX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetX
     * }
     */
    public static final OfInt resolveOffsetX$layout() {
        return resolveOffsetX$LAYOUT;
    }

    private static final long resolveOffsetX$OFFSET = $LAYOUT.byteOffset(groupElement("resolveOffsetX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetX
     * }
     */
    public static final long resolveOffsetX$offset() {
        return resolveOffsetX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetX
     * }
     */
    public static int resolveOffsetX(MemorySegment struct) {
        return struct.get(resolveOffsetX$LAYOUT, resolveOffsetX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetX
     * }
     */
    public static void resolveOffsetX(MemorySegment struct, int fieldValue) {
        struct.set(resolveOffsetX$LAYOUT, resolveOffsetX$OFFSET, fieldValue);
    }

    private static final OfInt resolveOffsetY$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resolveOffsetY"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetY
     * }
     */
    public static final OfInt resolveOffsetY$layout() {
        return resolveOffsetY$LAYOUT;
    }

    private static final long resolveOffsetY$OFFSET = $LAYOUT.byteOffset(groupElement("resolveOffsetY"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetY
     * }
     */
    public static final long resolveOffsetY$offset() {
        return resolveOffsetY$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetY
     * }
     */
    public static int resolveOffsetY(MemorySegment struct) {
        return struct.get(resolveOffsetY$LAYOUT, resolveOffsetY$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t resolveOffsetY
     * }
     */
    public static void resolveOffsetY(MemorySegment struct, int fieldValue) {
        struct.set(resolveOffsetY$LAYOUT, resolveOffsetY$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

