// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUCopyTextureForBrowserOptions {
 *     WGPUChainedStruct *nextInChain;
 *     WGPUBool flipY;
 *     WGPUBool needsColorSpaceConversion;
 *     WGPUAlphaMode srcAlphaMode;
 *     const float *srcTransferFunctionParameters;
 *     const float *conversionMatrix;
 *     const float *dstTransferFunctionParameters;
 *     WGPUAlphaMode dstAlphaMode;
 *     WGPUBool internalUsage;
 * }
 * }
 */
public class WGPUCopyTextureForBrowserOptions {

    WGPUCopyTextureForBrowserOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        webgpu_h.C_INT.withName("flipY"),
        webgpu_h.C_INT.withName("needsColorSpaceConversion"),
        webgpu_h.C_INT.withName("srcAlphaMode"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_POINTER.withName("srcTransferFunctionParameters"),
        webgpu_h.C_POINTER.withName("conversionMatrix"),
        webgpu_h.C_POINTER.withName("dstTransferFunctionParameters"),
        webgpu_h.C_INT.withName("dstAlphaMode"),
        webgpu_h.C_INT.withName("internalUsage")
    ).withName("WGPUCopyTextureForBrowserOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final OfInt flipY$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flipY"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool flipY
     * }
     */
    public static final OfInt flipY$layout() {
        return flipY$LAYOUT;
    }

    private static final long flipY$OFFSET = $LAYOUT.byteOffset(groupElement("flipY"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool flipY
     * }
     */
    public static final long flipY$offset() {
        return flipY$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool flipY
     * }
     */
    public static int flipY(MemorySegment struct) {
        return struct.get(flipY$LAYOUT, flipY$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool flipY
     * }
     */
    public static void flipY(MemorySegment struct, int fieldValue) {
        struct.set(flipY$LAYOUT, flipY$OFFSET, fieldValue);
    }

    private static final OfInt needsColorSpaceConversion$LAYOUT = (OfInt)$LAYOUT.select(groupElement("needsColorSpaceConversion"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool needsColorSpaceConversion
     * }
     */
    public static final OfInt needsColorSpaceConversion$layout() {
        return needsColorSpaceConversion$LAYOUT;
    }

    private static final long needsColorSpaceConversion$OFFSET = $LAYOUT.byteOffset(groupElement("needsColorSpaceConversion"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool needsColorSpaceConversion
     * }
     */
    public static final long needsColorSpaceConversion$offset() {
        return needsColorSpaceConversion$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool needsColorSpaceConversion
     * }
     */
    public static int needsColorSpaceConversion(MemorySegment struct) {
        return struct.get(needsColorSpaceConversion$LAYOUT, needsColorSpaceConversion$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool needsColorSpaceConversion
     * }
     */
    public static void needsColorSpaceConversion(MemorySegment struct, int fieldValue) {
        struct.set(needsColorSpaceConversion$LAYOUT, needsColorSpaceConversion$OFFSET, fieldValue);
    }

    private static final OfInt srcAlphaMode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("srcAlphaMode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUAlphaMode srcAlphaMode
     * }
     */
    public static final OfInt srcAlphaMode$layout() {
        return srcAlphaMode$LAYOUT;
    }

    private static final long srcAlphaMode$OFFSET = $LAYOUT.byteOffset(groupElement("srcAlphaMode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUAlphaMode srcAlphaMode
     * }
     */
    public static final long srcAlphaMode$offset() {
        return srcAlphaMode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUAlphaMode srcAlphaMode
     * }
     */
    public static int srcAlphaMode(MemorySegment struct) {
        return struct.get(srcAlphaMode$LAYOUT, srcAlphaMode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUAlphaMode srcAlphaMode
     * }
     */
    public static void srcAlphaMode(MemorySegment struct, int fieldValue) {
        struct.set(srcAlphaMode$LAYOUT, srcAlphaMode$OFFSET, fieldValue);
    }

    private static final AddressLayout srcTransferFunctionParameters$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("srcTransferFunctionParameters"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static final AddressLayout srcTransferFunctionParameters$layout() {
        return srcTransferFunctionParameters$LAYOUT;
    }

    private static final long srcTransferFunctionParameters$OFFSET = $LAYOUT.byteOffset(groupElement("srcTransferFunctionParameters"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static final long srcTransferFunctionParameters$offset() {
        return srcTransferFunctionParameters$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static MemorySegment srcTransferFunctionParameters(MemorySegment struct) {
        return struct.get(srcTransferFunctionParameters$LAYOUT, srcTransferFunctionParameters$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static void srcTransferFunctionParameters(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(srcTransferFunctionParameters$LAYOUT, srcTransferFunctionParameters$OFFSET, fieldValue);
    }

    private static final AddressLayout conversionMatrix$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("conversionMatrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *conversionMatrix
     * }
     */
    public static final AddressLayout conversionMatrix$layout() {
        return conversionMatrix$LAYOUT;
    }

    private static final long conversionMatrix$OFFSET = $LAYOUT.byteOffset(groupElement("conversionMatrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *conversionMatrix
     * }
     */
    public static final long conversionMatrix$offset() {
        return conversionMatrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *conversionMatrix
     * }
     */
    public static MemorySegment conversionMatrix(MemorySegment struct) {
        return struct.get(conversionMatrix$LAYOUT, conversionMatrix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *conversionMatrix
     * }
     */
    public static void conversionMatrix(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(conversionMatrix$LAYOUT, conversionMatrix$OFFSET, fieldValue);
    }

    private static final AddressLayout dstTransferFunctionParameters$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dstTransferFunctionParameters"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static final AddressLayout dstTransferFunctionParameters$layout() {
        return dstTransferFunctionParameters$LAYOUT;
    }

    private static final long dstTransferFunctionParameters$OFFSET = $LAYOUT.byteOffset(groupElement("dstTransferFunctionParameters"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static final long dstTransferFunctionParameters$offset() {
        return dstTransferFunctionParameters$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static MemorySegment dstTransferFunctionParameters(MemorySegment struct) {
        return struct.get(dstTransferFunctionParameters$LAYOUT, dstTransferFunctionParameters$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static void dstTransferFunctionParameters(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dstTransferFunctionParameters$LAYOUT, dstTransferFunctionParameters$OFFSET, fieldValue);
    }

    private static final OfInt dstAlphaMode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dstAlphaMode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUAlphaMode dstAlphaMode
     * }
     */
    public static final OfInt dstAlphaMode$layout() {
        return dstAlphaMode$LAYOUT;
    }

    private static final long dstAlphaMode$OFFSET = $LAYOUT.byteOffset(groupElement("dstAlphaMode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUAlphaMode dstAlphaMode
     * }
     */
    public static final long dstAlphaMode$offset() {
        return dstAlphaMode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUAlphaMode dstAlphaMode
     * }
     */
    public static int dstAlphaMode(MemorySegment struct) {
        return struct.get(dstAlphaMode$LAYOUT, dstAlphaMode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUAlphaMode dstAlphaMode
     * }
     */
    public static void dstAlphaMode(MemorySegment struct, int fieldValue) {
        struct.set(dstAlphaMode$LAYOUT, dstAlphaMode$OFFSET, fieldValue);
    }

    private static final OfInt internalUsage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("internalUsage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool internalUsage
     * }
     */
    public static final OfInt internalUsage$layout() {
        return internalUsage$LAYOUT;
    }

    private static final long internalUsage$OFFSET = $LAYOUT.byteOffset(groupElement("internalUsage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool internalUsage
     * }
     */
    public static final long internalUsage$offset() {
        return internalUsage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool internalUsage
     * }
     */
    public static int internalUsage(MemorySegment struct) {
        return struct.get(internalUsage$LAYOUT, internalUsage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool internalUsage
     * }
     */
    public static void internalUsage(MemorySegment struct, int fieldValue) {
        struct.set(internalUsage$LAYOUT, internalUsage$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

