// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUBindGroupLayoutEntry {
 *     WGPUChainedStruct *nextInChain;
 *     uint32_t binding;
 *     WGPUShaderStage visibility;
 *     uint32_t bindingArraySize;
 *     WGPUBufferBindingLayout buffer;
 *     WGPUSamplerBindingLayout sampler;
 *     WGPUTextureBindingLayout texture;
 *     WGPUStorageTextureBindingLayout storageTexture;
 * }
 * }
 */
public class WGPUBindGroupLayoutEntry {

    WGPUBindGroupLayoutEntry() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        webgpu_h.C_INT.withName("binding"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_LONG_LONG.withName("visibility"),
        webgpu_h.C_INT.withName("bindingArraySize"),
        MemoryLayout.paddingLayout(4),
        WGPUBufferBindingLayout.layout().withName("buffer"),
        WGPUSamplerBindingLayout.layout().withName("sampler"),
        WGPUTextureBindingLayout.layout().withName("texture"),
        WGPUStorageTextureBindingLayout.layout().withName("storageTexture")
    ).withName("WGPUBindGroupLayoutEntry");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final OfInt binding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("binding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t binding
     * }
     */
    public static final OfInt binding$layout() {
        return binding$LAYOUT;
    }

    private static final long binding$OFFSET = $LAYOUT.byteOffset(groupElement("binding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t binding
     * }
     */
    public static final long binding$offset() {
        return binding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t binding
     * }
     */
    public static int binding(MemorySegment struct) {
        return struct.get(binding$LAYOUT, binding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t binding
     * }
     */
    public static void binding(MemorySegment struct, int fieldValue) {
        struct.set(binding$LAYOUT, binding$OFFSET, fieldValue);
    }

    private static final OfLong visibility$LAYOUT = (OfLong)$LAYOUT.select(groupElement("visibility"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUShaderStage visibility
     * }
     */
    public static final OfLong visibility$layout() {
        return visibility$LAYOUT;
    }

    private static final long visibility$OFFSET = $LAYOUT.byteOffset(groupElement("visibility"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUShaderStage visibility
     * }
     */
    public static final long visibility$offset() {
        return visibility$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUShaderStage visibility
     * }
     */
    public static long visibility(MemorySegment struct) {
        return struct.get(visibility$LAYOUT, visibility$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUShaderStage visibility
     * }
     */
    public static void visibility(MemorySegment struct, long fieldValue) {
        struct.set(visibility$LAYOUT, visibility$OFFSET, fieldValue);
    }

    private static final OfInt bindingArraySize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bindingArraySize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t bindingArraySize
     * }
     */
    public static final OfInt bindingArraySize$layout() {
        return bindingArraySize$LAYOUT;
    }

    private static final long bindingArraySize$OFFSET = $LAYOUT.byteOffset(groupElement("bindingArraySize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t bindingArraySize
     * }
     */
    public static final long bindingArraySize$offset() {
        return bindingArraySize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t bindingArraySize
     * }
     */
    public static int bindingArraySize(MemorySegment struct) {
        return struct.get(bindingArraySize$LAYOUT, bindingArraySize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t bindingArraySize
     * }
     */
    public static void bindingArraySize(MemorySegment struct, int fieldValue) {
        struct.set(bindingArraySize$LAYOUT, bindingArraySize$OFFSET, fieldValue);
    }

    private static final GroupLayout buffer$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBufferBindingLayout buffer
     * }
     */
    public static final GroupLayout buffer$layout() {
        return buffer$LAYOUT;
    }

    private static final long buffer$OFFSET = $LAYOUT.byteOffset(groupElement("buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBufferBindingLayout buffer
     * }
     */
    public static final long buffer$offset() {
        return buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBufferBindingLayout buffer
     * }
     */
    public static MemorySegment buffer(MemorySegment struct) {
        return struct.asSlice(buffer$OFFSET, buffer$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBufferBindingLayout buffer
     * }
     */
    public static void buffer(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, buffer$OFFSET, buffer$LAYOUT.byteSize());
    }

    private static final GroupLayout sampler$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sampler"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUSamplerBindingLayout sampler
     * }
     */
    public static final GroupLayout sampler$layout() {
        return sampler$LAYOUT;
    }

    private static final long sampler$OFFSET = $LAYOUT.byteOffset(groupElement("sampler"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUSamplerBindingLayout sampler
     * }
     */
    public static final long sampler$offset() {
        return sampler$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUSamplerBindingLayout sampler
     * }
     */
    public static MemorySegment sampler(MemorySegment struct) {
        return struct.asSlice(sampler$OFFSET, sampler$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUSamplerBindingLayout sampler
     * }
     */
    public static void sampler(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sampler$OFFSET, sampler$LAYOUT.byteSize());
    }

    private static final GroupLayout texture$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("texture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUTextureBindingLayout texture
     * }
     */
    public static final GroupLayout texture$layout() {
        return texture$LAYOUT;
    }

    private static final long texture$OFFSET = $LAYOUT.byteOffset(groupElement("texture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUTextureBindingLayout texture
     * }
     */
    public static final long texture$offset() {
        return texture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUTextureBindingLayout texture
     * }
     */
    public static MemorySegment texture(MemorySegment struct) {
        return struct.asSlice(texture$OFFSET, texture$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUTextureBindingLayout texture
     * }
     */
    public static void texture(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, texture$OFFSET, texture$LAYOUT.byteSize());
    }

    private static final GroupLayout storageTexture$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("storageTexture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUStorageTextureBindingLayout storageTexture
     * }
     */
    public static final GroupLayout storageTexture$layout() {
        return storageTexture$LAYOUT;
    }

    private static final long storageTexture$OFFSET = $LAYOUT.byteOffset(groupElement("storageTexture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUStorageTextureBindingLayout storageTexture
     * }
     */
    public static final long storageTexture$offset() {
        return storageTexture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUStorageTextureBindingLayout storageTexture
     * }
     */
    public static MemorySegment storageTexture(MemorySegment struct) {
        return struct.asSlice(storageTexture$OFFSET, storageTexture$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUStorageTextureBindingLayout storageTexture
     * }
     */
    public static void storageTexture(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, storageTexture$OFFSET, storageTexture$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

