// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUDawnWireWGSLControl {
 *     WGPUChainedStruct chain;
 *     WGPUBool enableExperimental;
 *     WGPUBool enableUnsafe;
 *     WGPUBool enableTesting;
 * }
 * }
 */
public class WGPUDawnWireWGSLControl {

    WGPUDawnWireWGSLControl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("enableExperimental"),
        webgpu_h.C_INT.withName("enableUnsafe"),
        webgpu_h.C_INT.withName("enableTesting"),
        MemoryLayout.paddingLayout(4)
    ).withName("WGPUDawnWireWGSLControl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt enableExperimental$LAYOUT = (OfInt)$LAYOUT.select(groupElement("enableExperimental"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool enableExperimental
     * }
     */
    public static final OfInt enableExperimental$layout() {
        return enableExperimental$LAYOUT;
    }

    private static final long enableExperimental$OFFSET = $LAYOUT.byteOffset(groupElement("enableExperimental"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool enableExperimental
     * }
     */
    public static final long enableExperimental$offset() {
        return enableExperimental$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool enableExperimental
     * }
     */
    public static int enableExperimental(MemorySegment struct) {
        return struct.get(enableExperimental$LAYOUT, enableExperimental$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool enableExperimental
     * }
     */
    public static void enableExperimental(MemorySegment struct, int fieldValue) {
        struct.set(enableExperimental$LAYOUT, enableExperimental$OFFSET, fieldValue);
    }

    private static final OfInt enableUnsafe$LAYOUT = (OfInt)$LAYOUT.select(groupElement("enableUnsafe"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool enableUnsafe
     * }
     */
    public static final OfInt enableUnsafe$layout() {
        return enableUnsafe$LAYOUT;
    }

    private static final long enableUnsafe$OFFSET = $LAYOUT.byteOffset(groupElement("enableUnsafe"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool enableUnsafe
     * }
     */
    public static final long enableUnsafe$offset() {
        return enableUnsafe$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool enableUnsafe
     * }
     */
    public static int enableUnsafe(MemorySegment struct) {
        return struct.get(enableUnsafe$LAYOUT, enableUnsafe$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool enableUnsafe
     * }
     */
    public static void enableUnsafe(MemorySegment struct, int fieldValue) {
        struct.set(enableUnsafe$LAYOUT, enableUnsafe$OFFSET, fieldValue);
    }

    private static final OfInt enableTesting$LAYOUT = (OfInt)$LAYOUT.select(groupElement("enableTesting"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool enableTesting
     * }
     */
    public static final OfInt enableTesting$layout() {
        return enableTesting$LAYOUT;
    }

    private static final long enableTesting$OFFSET = $LAYOUT.byteOffset(groupElement("enableTesting"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool enableTesting
     * }
     */
    public static final long enableTesting$offset() {
        return enableTesting$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool enableTesting
     * }
     */
    public static int enableTesting(MemorySegment struct) {
        return struct.get(enableTesting$LAYOUT, enableTesting$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool enableTesting
     * }
     */
    public static void enableTesting(MemorySegment struct, int fieldValue) {
        struct.set(enableTesting$LAYOUT, enableTesting$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

