// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUAdapterPropertiesSubgroupMatrixConfigs {
 *     WGPUChainedStruct chain;
 *     size_t configCount;
 *     const WGPUSubgroupMatrixConfig *configs;
 * }
 * }
 */
public class WGPUAdapterPropertiesSubgroupMatrixConfigs {

    WGPUAdapterPropertiesSubgroupMatrixConfigs() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG.withName("configCount"),
        webgpu_h.C_POINTER.withName("configs")
    ).withName("WGPUAdapterPropertiesSubgroupMatrixConfigs");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong configCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("configCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t configCount
     * }
     */
    public static final OfLong configCount$layout() {
        return configCount$LAYOUT;
    }

    private static final long configCount$OFFSET = $LAYOUT.byteOffset(groupElement("configCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t configCount
     * }
     */
    public static final long configCount$offset() {
        return configCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t configCount
     * }
     */
    public static long configCount(MemorySegment struct) {
        return struct.get(configCount$LAYOUT, configCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t configCount
     * }
     */
    public static void configCount(MemorySegment struct, long fieldValue) {
        struct.set(configCount$LAYOUT, configCount$OFFSET, fieldValue);
    }

    private static final AddressLayout configs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("configs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUSubgroupMatrixConfig *configs
     * }
     */
    public static final AddressLayout configs$layout() {
        return configs$LAYOUT;
    }

    private static final long configs$OFFSET = $LAYOUT.byteOffset(groupElement("configs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUSubgroupMatrixConfig *configs
     * }
     */
    public static final long configs$offset() {
        return configs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUSubgroupMatrixConfig *configs
     * }
     */
    public static MemorySegment configs(MemorySegment struct) {
        return struct.get(configs$LAYOUT, configs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUSubgroupMatrixConfig *configs
     * }
     */
    public static void configs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(configs$LAYOUT, configs$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

