// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUYCbCrVkDescriptor {
 *     WGPUChainedStruct chain;
 *     uint32_t vkFormat;
 *     uint32_t vkYCbCrModel;
 *     uint32_t vkYCbCrRange;
 *     uint32_t vkComponentSwizzleRed;
 *     uint32_t vkComponentSwizzleGreen;
 *     uint32_t vkComponentSwizzleBlue;
 *     uint32_t vkComponentSwizzleAlpha;
 *     uint32_t vkXChromaOffset;
 *     uint32_t vkYChromaOffset;
 *     WGPUFilterMode vkChromaFilter;
 *     WGPUBool forceExplicitReconstruction;
 *     uint64_t externalFormat;
 * }
 * }
 */
public class WGPUYCbCrVkDescriptor {

    WGPUYCbCrVkDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("vkFormat"),
        webgpu_h.C_INT.withName("vkYCbCrModel"),
        webgpu_h.C_INT.withName("vkYCbCrRange"),
        webgpu_h.C_INT.withName("vkComponentSwizzleRed"),
        webgpu_h.C_INT.withName("vkComponentSwizzleGreen"),
        webgpu_h.C_INT.withName("vkComponentSwizzleBlue"),
        webgpu_h.C_INT.withName("vkComponentSwizzleAlpha"),
        webgpu_h.C_INT.withName("vkXChromaOffset"),
        webgpu_h.C_INT.withName("vkYChromaOffset"),
        webgpu_h.C_INT.withName("vkChromaFilter"),
        webgpu_h.C_INT.withName("forceExplicitReconstruction"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_LONG_LONG.withName("externalFormat")
    ).withName("WGPUYCbCrVkDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt vkFormat$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkFormat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkFormat
     * }
     */
    public static final OfInt vkFormat$layout() {
        return vkFormat$LAYOUT;
    }

    private static final long vkFormat$OFFSET = $LAYOUT.byteOffset(groupElement("vkFormat"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkFormat
     * }
     */
    public static final long vkFormat$offset() {
        return vkFormat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkFormat
     * }
     */
    public static int vkFormat(MemorySegment struct) {
        return struct.get(vkFormat$LAYOUT, vkFormat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkFormat
     * }
     */
    public static void vkFormat(MemorySegment struct, int fieldValue) {
        struct.set(vkFormat$LAYOUT, vkFormat$OFFSET, fieldValue);
    }

    private static final OfInt vkYCbCrModel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkYCbCrModel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrModel
     * }
     */
    public static final OfInt vkYCbCrModel$layout() {
        return vkYCbCrModel$LAYOUT;
    }

    private static final long vkYCbCrModel$OFFSET = $LAYOUT.byteOffset(groupElement("vkYCbCrModel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrModel
     * }
     */
    public static final long vkYCbCrModel$offset() {
        return vkYCbCrModel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrModel
     * }
     */
    public static int vkYCbCrModel(MemorySegment struct) {
        return struct.get(vkYCbCrModel$LAYOUT, vkYCbCrModel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrModel
     * }
     */
    public static void vkYCbCrModel(MemorySegment struct, int fieldValue) {
        struct.set(vkYCbCrModel$LAYOUT, vkYCbCrModel$OFFSET, fieldValue);
    }

    private static final OfInt vkYCbCrRange$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkYCbCrRange"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrRange
     * }
     */
    public static final OfInt vkYCbCrRange$layout() {
        return vkYCbCrRange$LAYOUT;
    }

    private static final long vkYCbCrRange$OFFSET = $LAYOUT.byteOffset(groupElement("vkYCbCrRange"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrRange
     * }
     */
    public static final long vkYCbCrRange$offset() {
        return vkYCbCrRange$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrRange
     * }
     */
    public static int vkYCbCrRange(MemorySegment struct) {
        return struct.get(vkYCbCrRange$LAYOUT, vkYCbCrRange$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkYCbCrRange
     * }
     */
    public static void vkYCbCrRange(MemorySegment struct, int fieldValue) {
        struct.set(vkYCbCrRange$LAYOUT, vkYCbCrRange$OFFSET, fieldValue);
    }

    private static final OfInt vkComponentSwizzleRed$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkComponentSwizzleRed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleRed
     * }
     */
    public static final OfInt vkComponentSwizzleRed$layout() {
        return vkComponentSwizzleRed$LAYOUT;
    }

    private static final long vkComponentSwizzleRed$OFFSET = $LAYOUT.byteOffset(groupElement("vkComponentSwizzleRed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleRed
     * }
     */
    public static final long vkComponentSwizzleRed$offset() {
        return vkComponentSwizzleRed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleRed
     * }
     */
    public static int vkComponentSwizzleRed(MemorySegment struct) {
        return struct.get(vkComponentSwizzleRed$LAYOUT, vkComponentSwizzleRed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleRed
     * }
     */
    public static void vkComponentSwizzleRed(MemorySegment struct, int fieldValue) {
        struct.set(vkComponentSwizzleRed$LAYOUT, vkComponentSwizzleRed$OFFSET, fieldValue);
    }

    private static final OfInt vkComponentSwizzleGreen$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkComponentSwizzleGreen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleGreen
     * }
     */
    public static final OfInt vkComponentSwizzleGreen$layout() {
        return vkComponentSwizzleGreen$LAYOUT;
    }

    private static final long vkComponentSwizzleGreen$OFFSET = $LAYOUT.byteOffset(groupElement("vkComponentSwizzleGreen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleGreen
     * }
     */
    public static final long vkComponentSwizzleGreen$offset() {
        return vkComponentSwizzleGreen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleGreen
     * }
     */
    public static int vkComponentSwizzleGreen(MemorySegment struct) {
        return struct.get(vkComponentSwizzleGreen$LAYOUT, vkComponentSwizzleGreen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleGreen
     * }
     */
    public static void vkComponentSwizzleGreen(MemorySegment struct, int fieldValue) {
        struct.set(vkComponentSwizzleGreen$LAYOUT, vkComponentSwizzleGreen$OFFSET, fieldValue);
    }

    private static final OfInt vkComponentSwizzleBlue$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkComponentSwizzleBlue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleBlue
     * }
     */
    public static final OfInt vkComponentSwizzleBlue$layout() {
        return vkComponentSwizzleBlue$LAYOUT;
    }

    private static final long vkComponentSwizzleBlue$OFFSET = $LAYOUT.byteOffset(groupElement("vkComponentSwizzleBlue"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleBlue
     * }
     */
    public static final long vkComponentSwizzleBlue$offset() {
        return vkComponentSwizzleBlue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleBlue
     * }
     */
    public static int vkComponentSwizzleBlue(MemorySegment struct) {
        return struct.get(vkComponentSwizzleBlue$LAYOUT, vkComponentSwizzleBlue$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleBlue
     * }
     */
    public static void vkComponentSwizzleBlue(MemorySegment struct, int fieldValue) {
        struct.set(vkComponentSwizzleBlue$LAYOUT, vkComponentSwizzleBlue$OFFSET, fieldValue);
    }

    private static final OfInt vkComponentSwizzleAlpha$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkComponentSwizzleAlpha"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleAlpha
     * }
     */
    public static final OfInt vkComponentSwizzleAlpha$layout() {
        return vkComponentSwizzleAlpha$LAYOUT;
    }

    private static final long vkComponentSwizzleAlpha$OFFSET = $LAYOUT.byteOffset(groupElement("vkComponentSwizzleAlpha"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleAlpha
     * }
     */
    public static final long vkComponentSwizzleAlpha$offset() {
        return vkComponentSwizzleAlpha$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleAlpha
     * }
     */
    public static int vkComponentSwizzleAlpha(MemorySegment struct) {
        return struct.get(vkComponentSwizzleAlpha$LAYOUT, vkComponentSwizzleAlpha$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkComponentSwizzleAlpha
     * }
     */
    public static void vkComponentSwizzleAlpha(MemorySegment struct, int fieldValue) {
        struct.set(vkComponentSwizzleAlpha$LAYOUT, vkComponentSwizzleAlpha$OFFSET, fieldValue);
    }

    private static final OfInt vkXChromaOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkXChromaOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkXChromaOffset
     * }
     */
    public static final OfInt vkXChromaOffset$layout() {
        return vkXChromaOffset$LAYOUT;
    }

    private static final long vkXChromaOffset$OFFSET = $LAYOUT.byteOffset(groupElement("vkXChromaOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkXChromaOffset
     * }
     */
    public static final long vkXChromaOffset$offset() {
        return vkXChromaOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkXChromaOffset
     * }
     */
    public static int vkXChromaOffset(MemorySegment struct) {
        return struct.get(vkXChromaOffset$LAYOUT, vkXChromaOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkXChromaOffset
     * }
     */
    public static void vkXChromaOffset(MemorySegment struct, int fieldValue) {
        struct.set(vkXChromaOffset$LAYOUT, vkXChromaOffset$OFFSET, fieldValue);
    }

    private static final OfInt vkYChromaOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkYChromaOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vkYChromaOffset
     * }
     */
    public static final OfInt vkYChromaOffset$layout() {
        return vkYChromaOffset$LAYOUT;
    }

    private static final long vkYChromaOffset$OFFSET = $LAYOUT.byteOffset(groupElement("vkYChromaOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vkYChromaOffset
     * }
     */
    public static final long vkYChromaOffset$offset() {
        return vkYChromaOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vkYChromaOffset
     * }
     */
    public static int vkYChromaOffset(MemorySegment struct) {
        return struct.get(vkYChromaOffset$LAYOUT, vkYChromaOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vkYChromaOffset
     * }
     */
    public static void vkYChromaOffset(MemorySegment struct, int fieldValue) {
        struct.set(vkYChromaOffset$LAYOUT, vkYChromaOffset$OFFSET, fieldValue);
    }

    private static final OfInt vkChromaFilter$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vkChromaFilter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUFilterMode vkChromaFilter
     * }
     */
    public static final OfInt vkChromaFilter$layout() {
        return vkChromaFilter$LAYOUT;
    }

    private static final long vkChromaFilter$OFFSET = $LAYOUT.byteOffset(groupElement("vkChromaFilter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUFilterMode vkChromaFilter
     * }
     */
    public static final long vkChromaFilter$offset() {
        return vkChromaFilter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUFilterMode vkChromaFilter
     * }
     */
    public static int vkChromaFilter(MemorySegment struct) {
        return struct.get(vkChromaFilter$LAYOUT, vkChromaFilter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUFilterMode vkChromaFilter
     * }
     */
    public static void vkChromaFilter(MemorySegment struct, int fieldValue) {
        struct.set(vkChromaFilter$LAYOUT, vkChromaFilter$OFFSET, fieldValue);
    }

    private static final OfInt forceExplicitReconstruction$LAYOUT = (OfInt)$LAYOUT.select(groupElement("forceExplicitReconstruction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool forceExplicitReconstruction
     * }
     */
    public static final OfInt forceExplicitReconstruction$layout() {
        return forceExplicitReconstruction$LAYOUT;
    }

    private static final long forceExplicitReconstruction$OFFSET = $LAYOUT.byteOffset(groupElement("forceExplicitReconstruction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool forceExplicitReconstruction
     * }
     */
    public static final long forceExplicitReconstruction$offset() {
        return forceExplicitReconstruction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool forceExplicitReconstruction
     * }
     */
    public static int forceExplicitReconstruction(MemorySegment struct) {
        return struct.get(forceExplicitReconstruction$LAYOUT, forceExplicitReconstruction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool forceExplicitReconstruction
     * }
     */
    public static void forceExplicitReconstruction(MemorySegment struct, int fieldValue) {
        struct.set(forceExplicitReconstruction$LAYOUT, forceExplicitReconstruction$OFFSET, fieldValue);
    }

    private static final OfLong externalFormat$LAYOUT = (OfLong)$LAYOUT.select(groupElement("externalFormat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t externalFormat
     * }
     */
    public static final OfLong externalFormat$layout() {
        return externalFormat$LAYOUT;
    }

    private static final long externalFormat$OFFSET = $LAYOUT.byteOffset(groupElement("externalFormat"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t externalFormat
     * }
     */
    public static final long externalFormat$offset() {
        return externalFormat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t externalFormat
     * }
     */
    public static long externalFormat(MemorySegment struct) {
        return struct.get(externalFormat$LAYOUT, externalFormat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t externalFormat
     * }
     */
    public static void externalFormat(MemorySegment struct, long fieldValue) {
        struct.set(externalFormat$LAYOUT, externalFormat$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

