// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUBufferHostMappedPointer {
 *     WGPUChainedStruct chain;
 *     void *pointer;
 *     WGPUCallback disposeCallback;
 *     void *userdata;
 * }
 * }
 */
public class WGPUBufferHostMappedPointer {

    WGPUBufferHostMappedPointer() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_POINTER.withName("pointer"),
        webgpu_h.C_POINTER.withName("disposeCallback"),
        webgpu_h.C_POINTER.withName("userdata")
    ).withName("WGPUBufferHostMappedPointer");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final AddressLayout pointer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pointer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pointer
     * }
     */
    public static final AddressLayout pointer$layout() {
        return pointer$LAYOUT;
    }

    private static final long pointer$OFFSET = $LAYOUT.byteOffset(groupElement("pointer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pointer
     * }
     */
    public static final long pointer$offset() {
        return pointer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pointer
     * }
     */
    public static MemorySegment pointer(MemorySegment struct) {
        return struct.get(pointer$LAYOUT, pointer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pointer
     * }
     */
    public static void pointer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pointer$LAYOUT, pointer$OFFSET, fieldValue);
    }

    private static final AddressLayout disposeCallback$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("disposeCallback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUCallback disposeCallback
     * }
     */
    public static final AddressLayout disposeCallback$layout() {
        return disposeCallback$LAYOUT;
    }

    private static final long disposeCallback$OFFSET = $LAYOUT.byteOffset(groupElement("disposeCallback"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUCallback disposeCallback
     * }
     */
    public static final long disposeCallback$offset() {
        return disposeCallback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUCallback disposeCallback
     * }
     */
    public static MemorySegment disposeCallback(MemorySegment struct) {
        return struct.get(disposeCallback$LAYOUT, disposeCallback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUCallback disposeCallback
     * }
     */
    public static void disposeCallback(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(disposeCallback$LAYOUT, disposeCallback$OFFSET, fieldValue);
    }

    private static final AddressLayout userdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static final AddressLayout userdata$layout() {
        return userdata$LAYOUT;
    }

    private static final long userdata$OFFSET = $LAYOUT.byteOffset(groupElement("userdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static final long userdata$offset() {
        return userdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static MemorySegment userdata(MemorySegment struct) {
        return struct.get(userdata$LAYOUT, userdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static void userdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userdata$LAYOUT, userdata$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

