// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUSubgroupMatrixConfig {
 *     WGPUSubgroupMatrixComponentType componentType;
 *     WGPUSubgroupMatrixComponentType resultComponentType;
 *     uint32_t M;
 *     uint32_t N;
 *     uint32_t K;
 * }
 * }
 */
public class WGPUSubgroupMatrixConfig {

    WGPUSubgroupMatrixConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_INT.withName("componentType"),
        webgpu_h.C_INT.withName("resultComponentType"),
        webgpu_h.C_INT.withName("M"),
        webgpu_h.C_INT.withName("N"),
        webgpu_h.C_INT.withName("K")
    ).withName("WGPUSubgroupMatrixConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt componentType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("componentType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType componentType
     * }
     */
    public static final OfInt componentType$layout() {
        return componentType$LAYOUT;
    }

    private static final long componentType$OFFSET = $LAYOUT.byteOffset(groupElement("componentType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType componentType
     * }
     */
    public static final long componentType$offset() {
        return componentType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType componentType
     * }
     */
    public static int componentType(MemorySegment struct) {
        return struct.get(componentType$LAYOUT, componentType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType componentType
     * }
     */
    public static void componentType(MemorySegment struct, int fieldValue) {
        struct.set(componentType$LAYOUT, componentType$OFFSET, fieldValue);
    }

    private static final OfInt resultComponentType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resultComponentType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType resultComponentType
     * }
     */
    public static final OfInt resultComponentType$layout() {
        return resultComponentType$LAYOUT;
    }

    private static final long resultComponentType$OFFSET = $LAYOUT.byteOffset(groupElement("resultComponentType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType resultComponentType
     * }
     */
    public static final long resultComponentType$offset() {
        return resultComponentType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType resultComponentType
     * }
     */
    public static int resultComponentType(MemorySegment struct) {
        return struct.get(resultComponentType$LAYOUT, resultComponentType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUSubgroupMatrixComponentType resultComponentType
     * }
     */
    public static void resultComponentType(MemorySegment struct, int fieldValue) {
        struct.set(resultComponentType$LAYOUT, resultComponentType$OFFSET, fieldValue);
    }

    private static final OfInt M$LAYOUT = (OfInt)$LAYOUT.select(groupElement("M"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t M
     * }
     */
    public static final OfInt M$layout() {
        return M$LAYOUT;
    }

    private static final long M$OFFSET = $LAYOUT.byteOffset(groupElement("M"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t M
     * }
     */
    public static final long M$offset() {
        return M$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t M
     * }
     */
    public static int M(MemorySegment struct) {
        return struct.get(M$LAYOUT, M$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t M
     * }
     */
    public static void M(MemorySegment struct, int fieldValue) {
        struct.set(M$LAYOUT, M$OFFSET, fieldValue);
    }

    private static final OfInt N$LAYOUT = (OfInt)$LAYOUT.select(groupElement("N"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t N
     * }
     */
    public static final OfInt N$layout() {
        return N$LAYOUT;
    }

    private static final long N$OFFSET = $LAYOUT.byteOffset(groupElement("N"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t N
     * }
     */
    public static final long N$offset() {
        return N$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t N
     * }
     */
    public static int N(MemorySegment struct) {
        return struct.get(N$LAYOUT, N$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t N
     * }
     */
    public static void N(MemorySegment struct, int fieldValue) {
        struct.set(N$LAYOUT, N$OFFSET, fieldValue);
    }

    private static final OfInt K$LAYOUT = (OfInt)$LAYOUT.select(groupElement("K"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t K
     * }
     */
    public static final OfInt K$layout() {
        return K$LAYOUT;
    }

    private static final long K$OFFSET = $LAYOUT.byteOffset(groupElement("K"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t K
     * }
     */
    public static final long K$offset() {
        return K$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t K
     * }
     */
    public static int K(MemorySegment struct) {
        return struct.get(K$LAYOUT, K$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t K
     * }
     */
    public static void K(MemorySegment struct, int fieldValue) {
        struct.set(K$LAYOUT, K$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

