// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUExternalTextureDescriptor {
 *     WGPUChainedStruct *nextInChain;
 *     WGPUStringView label;
 *     WGPUTextureView plane0;
 *     WGPUTextureView plane1;
 *     WGPUOrigin2D cropOrigin;
 *     WGPUExtent2D cropSize;
 *     WGPUExtent2D apparentSize;
 *     WGPUBool doYuvToRgbConversionOnly;
 *     const float *yuvToRgbConversionMatrix;
 *     const float *srcTransferFunctionParameters;
 *     const float *dstTransferFunctionParameters;
 *     const float *gamutConversionMatrix;
 *     WGPUBool mirrored;
 *     WGPUExternalTextureRotation rotation;
 * }
 * }
 */
public class WGPUExternalTextureDescriptor {

    WGPUExternalTextureDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        WGPUStringView.layout().withName("label"),
        webgpu_h.C_POINTER.withName("plane0"),
        webgpu_h.C_POINTER.withName("plane1"),
        WGPUOrigin2D.layout().withName("cropOrigin"),
        WGPUExtent2D.layout().withName("cropSize"),
        WGPUExtent2D.layout().withName("apparentSize"),
        webgpu_h.C_INT.withName("doYuvToRgbConversionOnly"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_POINTER.withName("yuvToRgbConversionMatrix"),
        webgpu_h.C_POINTER.withName("srcTransferFunctionParameters"),
        webgpu_h.C_POINTER.withName("dstTransferFunctionParameters"),
        webgpu_h.C_POINTER.withName("gamutConversionMatrix"),
        webgpu_h.C_INT.withName("mirrored"),
        webgpu_h.C_INT.withName("rotation")
    ).withName("WGPUExternalTextureDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final GroupLayout label$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("label"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUStringView label
     * }
     */
    public static final GroupLayout label$layout() {
        return label$LAYOUT;
    }

    private static final long label$OFFSET = $LAYOUT.byteOffset(groupElement("label"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUStringView label
     * }
     */
    public static final long label$offset() {
        return label$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUStringView label
     * }
     */
    public static MemorySegment label(MemorySegment struct) {
        return struct.asSlice(label$OFFSET, label$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUStringView label
     * }
     */
    public static void label(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, label$OFFSET, label$LAYOUT.byteSize());
    }

    private static final AddressLayout plane0$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("plane0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUTextureView plane0
     * }
     */
    public static final AddressLayout plane0$layout() {
        return plane0$LAYOUT;
    }

    private static final long plane0$OFFSET = $LAYOUT.byteOffset(groupElement("plane0"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUTextureView plane0
     * }
     */
    public static final long plane0$offset() {
        return plane0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUTextureView plane0
     * }
     */
    public static MemorySegment plane0(MemorySegment struct) {
        return struct.get(plane0$LAYOUT, plane0$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUTextureView plane0
     * }
     */
    public static void plane0(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(plane0$LAYOUT, plane0$OFFSET, fieldValue);
    }

    private static final AddressLayout plane1$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("plane1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUTextureView plane1
     * }
     */
    public static final AddressLayout plane1$layout() {
        return plane1$LAYOUT;
    }

    private static final long plane1$OFFSET = $LAYOUT.byteOffset(groupElement("plane1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUTextureView plane1
     * }
     */
    public static final long plane1$offset() {
        return plane1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUTextureView plane1
     * }
     */
    public static MemorySegment plane1(MemorySegment struct) {
        return struct.get(plane1$LAYOUT, plane1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUTextureView plane1
     * }
     */
    public static void plane1(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(plane1$LAYOUT, plane1$OFFSET, fieldValue);
    }

    private static final GroupLayout cropOrigin$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cropOrigin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUOrigin2D cropOrigin
     * }
     */
    public static final GroupLayout cropOrigin$layout() {
        return cropOrigin$LAYOUT;
    }

    private static final long cropOrigin$OFFSET = $LAYOUT.byteOffset(groupElement("cropOrigin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUOrigin2D cropOrigin
     * }
     */
    public static final long cropOrigin$offset() {
        return cropOrigin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUOrigin2D cropOrigin
     * }
     */
    public static MemorySegment cropOrigin(MemorySegment struct) {
        return struct.asSlice(cropOrigin$OFFSET, cropOrigin$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUOrigin2D cropOrigin
     * }
     */
    public static void cropOrigin(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cropOrigin$OFFSET, cropOrigin$LAYOUT.byteSize());
    }

    private static final GroupLayout cropSize$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cropSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUExtent2D cropSize
     * }
     */
    public static final GroupLayout cropSize$layout() {
        return cropSize$LAYOUT;
    }

    private static final long cropSize$OFFSET = $LAYOUT.byteOffset(groupElement("cropSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUExtent2D cropSize
     * }
     */
    public static final long cropSize$offset() {
        return cropSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUExtent2D cropSize
     * }
     */
    public static MemorySegment cropSize(MemorySegment struct) {
        return struct.asSlice(cropSize$OFFSET, cropSize$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUExtent2D cropSize
     * }
     */
    public static void cropSize(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cropSize$OFFSET, cropSize$LAYOUT.byteSize());
    }

    private static final GroupLayout apparentSize$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("apparentSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUExtent2D apparentSize
     * }
     */
    public static final GroupLayout apparentSize$layout() {
        return apparentSize$LAYOUT;
    }

    private static final long apparentSize$OFFSET = $LAYOUT.byteOffset(groupElement("apparentSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUExtent2D apparentSize
     * }
     */
    public static final long apparentSize$offset() {
        return apparentSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUExtent2D apparentSize
     * }
     */
    public static MemorySegment apparentSize(MemorySegment struct) {
        return struct.asSlice(apparentSize$OFFSET, apparentSize$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUExtent2D apparentSize
     * }
     */
    public static void apparentSize(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, apparentSize$OFFSET, apparentSize$LAYOUT.byteSize());
    }

    private static final OfInt doYuvToRgbConversionOnly$LAYOUT = (OfInt)$LAYOUT.select(groupElement("doYuvToRgbConversionOnly"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool doYuvToRgbConversionOnly
     * }
     */
    public static final OfInt doYuvToRgbConversionOnly$layout() {
        return doYuvToRgbConversionOnly$LAYOUT;
    }

    private static final long doYuvToRgbConversionOnly$OFFSET = $LAYOUT.byteOffset(groupElement("doYuvToRgbConversionOnly"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool doYuvToRgbConversionOnly
     * }
     */
    public static final long doYuvToRgbConversionOnly$offset() {
        return doYuvToRgbConversionOnly$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool doYuvToRgbConversionOnly
     * }
     */
    public static int doYuvToRgbConversionOnly(MemorySegment struct) {
        return struct.get(doYuvToRgbConversionOnly$LAYOUT, doYuvToRgbConversionOnly$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool doYuvToRgbConversionOnly
     * }
     */
    public static void doYuvToRgbConversionOnly(MemorySegment struct, int fieldValue) {
        struct.set(doYuvToRgbConversionOnly$LAYOUT, doYuvToRgbConversionOnly$OFFSET, fieldValue);
    }

    private static final AddressLayout yuvToRgbConversionMatrix$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("yuvToRgbConversionMatrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *yuvToRgbConversionMatrix
     * }
     */
    public static final AddressLayout yuvToRgbConversionMatrix$layout() {
        return yuvToRgbConversionMatrix$LAYOUT;
    }

    private static final long yuvToRgbConversionMatrix$OFFSET = $LAYOUT.byteOffset(groupElement("yuvToRgbConversionMatrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *yuvToRgbConversionMatrix
     * }
     */
    public static final long yuvToRgbConversionMatrix$offset() {
        return yuvToRgbConversionMatrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *yuvToRgbConversionMatrix
     * }
     */
    public static MemorySegment yuvToRgbConversionMatrix(MemorySegment struct) {
        return struct.get(yuvToRgbConversionMatrix$LAYOUT, yuvToRgbConversionMatrix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *yuvToRgbConversionMatrix
     * }
     */
    public static void yuvToRgbConversionMatrix(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(yuvToRgbConversionMatrix$LAYOUT, yuvToRgbConversionMatrix$OFFSET, fieldValue);
    }

    private static final AddressLayout srcTransferFunctionParameters$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("srcTransferFunctionParameters"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static final AddressLayout srcTransferFunctionParameters$layout() {
        return srcTransferFunctionParameters$LAYOUT;
    }

    private static final long srcTransferFunctionParameters$OFFSET = $LAYOUT.byteOffset(groupElement("srcTransferFunctionParameters"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static final long srcTransferFunctionParameters$offset() {
        return srcTransferFunctionParameters$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static MemorySegment srcTransferFunctionParameters(MemorySegment struct) {
        return struct.get(srcTransferFunctionParameters$LAYOUT, srcTransferFunctionParameters$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *srcTransferFunctionParameters
     * }
     */
    public static void srcTransferFunctionParameters(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(srcTransferFunctionParameters$LAYOUT, srcTransferFunctionParameters$OFFSET, fieldValue);
    }

    private static final AddressLayout dstTransferFunctionParameters$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dstTransferFunctionParameters"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static final AddressLayout dstTransferFunctionParameters$layout() {
        return dstTransferFunctionParameters$LAYOUT;
    }

    private static final long dstTransferFunctionParameters$OFFSET = $LAYOUT.byteOffset(groupElement("dstTransferFunctionParameters"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static final long dstTransferFunctionParameters$offset() {
        return dstTransferFunctionParameters$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static MemorySegment dstTransferFunctionParameters(MemorySegment struct) {
        return struct.get(dstTransferFunctionParameters$LAYOUT, dstTransferFunctionParameters$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *dstTransferFunctionParameters
     * }
     */
    public static void dstTransferFunctionParameters(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dstTransferFunctionParameters$LAYOUT, dstTransferFunctionParameters$OFFSET, fieldValue);
    }

    private static final AddressLayout gamutConversionMatrix$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("gamutConversionMatrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *gamutConversionMatrix
     * }
     */
    public static final AddressLayout gamutConversionMatrix$layout() {
        return gamutConversionMatrix$LAYOUT;
    }

    private static final long gamutConversionMatrix$OFFSET = $LAYOUT.byteOffset(groupElement("gamutConversionMatrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *gamutConversionMatrix
     * }
     */
    public static final long gamutConversionMatrix$offset() {
        return gamutConversionMatrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *gamutConversionMatrix
     * }
     */
    public static MemorySegment gamutConversionMatrix(MemorySegment struct) {
        return struct.get(gamutConversionMatrix$LAYOUT, gamutConversionMatrix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *gamutConversionMatrix
     * }
     */
    public static void gamutConversionMatrix(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(gamutConversionMatrix$LAYOUT, gamutConversionMatrix$OFFSET, fieldValue);
    }

    private static final OfInt mirrored$LAYOUT = (OfInt)$LAYOUT.select(groupElement("mirrored"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool mirrored
     * }
     */
    public static final OfInt mirrored$layout() {
        return mirrored$LAYOUT;
    }

    private static final long mirrored$OFFSET = $LAYOUT.byteOffset(groupElement("mirrored"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool mirrored
     * }
     */
    public static final long mirrored$offset() {
        return mirrored$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool mirrored
     * }
     */
    public static int mirrored(MemorySegment struct) {
        return struct.get(mirrored$LAYOUT, mirrored$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool mirrored
     * }
     */
    public static void mirrored(MemorySegment struct, int fieldValue) {
        struct.set(mirrored$LAYOUT, mirrored$OFFSET, fieldValue);
    }

    private static final OfInt rotation$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rotation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUExternalTextureRotation rotation
     * }
     */
    public static final OfInt rotation$layout() {
        return rotation$LAYOUT;
    }

    private static final long rotation$OFFSET = $LAYOUT.byteOffset(groupElement("rotation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUExternalTextureRotation rotation
     * }
     */
    public static final long rotation$offset() {
        return rotation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUExternalTextureRotation rotation
     * }
     */
    public static int rotation(MemorySegment struct) {
        return struct.get(rotation$LAYOUT, rotation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUExternalTextureRotation rotation
     * }
     */
    public static void rotation(MemorySegment struct, int fieldValue) {
        struct.set(rotation$LAYOUT, rotation$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

