// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUPipelineLayoutPixelLocalStorage {
 *     WGPUChainedStruct chain;
 *     uint64_t totalPixelLocalStorageSize;
 *     size_t storageAttachmentCount;
 *     const WGPUPipelineLayoutStorageAttachment *storageAttachments;
 * }
 * }
 */
public class WGPUPipelineLayoutPixelLocalStorage {

    WGPUPipelineLayoutPixelLocalStorage() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG_LONG.withName("totalPixelLocalStorageSize"),
        webgpu_h.C_LONG.withName("storageAttachmentCount"),
        webgpu_h.C_POINTER.withName("storageAttachments")
    ).withName("WGPUPipelineLayoutPixelLocalStorage");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong totalPixelLocalStorageSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("totalPixelLocalStorageSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t totalPixelLocalStorageSize
     * }
     */
    public static final OfLong totalPixelLocalStorageSize$layout() {
        return totalPixelLocalStorageSize$LAYOUT;
    }

    private static final long totalPixelLocalStorageSize$OFFSET = $LAYOUT.byteOffset(groupElement("totalPixelLocalStorageSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t totalPixelLocalStorageSize
     * }
     */
    public static final long totalPixelLocalStorageSize$offset() {
        return totalPixelLocalStorageSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t totalPixelLocalStorageSize
     * }
     */
    public static long totalPixelLocalStorageSize(MemorySegment struct) {
        return struct.get(totalPixelLocalStorageSize$LAYOUT, totalPixelLocalStorageSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t totalPixelLocalStorageSize
     * }
     */
    public static void totalPixelLocalStorageSize(MemorySegment struct, long fieldValue) {
        struct.set(totalPixelLocalStorageSize$LAYOUT, totalPixelLocalStorageSize$OFFSET, fieldValue);
    }

    private static final OfLong storageAttachmentCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("storageAttachmentCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t storageAttachmentCount
     * }
     */
    public static final OfLong storageAttachmentCount$layout() {
        return storageAttachmentCount$LAYOUT;
    }

    private static final long storageAttachmentCount$OFFSET = $LAYOUT.byteOffset(groupElement("storageAttachmentCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t storageAttachmentCount
     * }
     */
    public static final long storageAttachmentCount$offset() {
        return storageAttachmentCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t storageAttachmentCount
     * }
     */
    public static long storageAttachmentCount(MemorySegment struct) {
        return struct.get(storageAttachmentCount$LAYOUT, storageAttachmentCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t storageAttachmentCount
     * }
     */
    public static void storageAttachmentCount(MemorySegment struct, long fieldValue) {
        struct.set(storageAttachmentCount$LAYOUT, storageAttachmentCount$OFFSET, fieldValue);
    }

    private static final AddressLayout storageAttachments$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("storageAttachments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUPipelineLayoutStorageAttachment *storageAttachments
     * }
     */
    public static final AddressLayout storageAttachments$layout() {
        return storageAttachments$LAYOUT;
    }

    private static final long storageAttachments$OFFSET = $LAYOUT.byteOffset(groupElement("storageAttachments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUPipelineLayoutStorageAttachment *storageAttachments
     * }
     */
    public static final long storageAttachments$offset() {
        return storageAttachments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUPipelineLayoutStorageAttachment *storageAttachments
     * }
     */
    public static MemorySegment storageAttachments(MemorySegment struct) {
        return struct.get(storageAttachments$LAYOUT, storageAttachments$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUPipelineLayoutStorageAttachment *storageAttachments
     * }
     */
    public static void storageAttachments(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(storageAttachments$LAYOUT, storageAttachments$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

