// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUSharedTextureMemoryZirconHandleDescriptor {
 *     WGPUChainedStruct chain;
 *     uint32_t memoryFD;
 *     uint64_t allocationSize;
 * }
 * }
 */
public class WGPUSharedTextureMemoryZirconHandleDescriptor {

    WGPUSharedTextureMemoryZirconHandleDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("memoryFD"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_LONG_LONG.withName("allocationSize")
    ).withName("WGPUSharedTextureMemoryZirconHandleDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt memoryFD$LAYOUT = (OfInt)$LAYOUT.select(groupElement("memoryFD"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t memoryFD
     * }
     */
    public static final OfInt memoryFD$layout() {
        return memoryFD$LAYOUT;
    }

    private static final long memoryFD$OFFSET = $LAYOUT.byteOffset(groupElement("memoryFD"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t memoryFD
     * }
     */
    public static final long memoryFD$offset() {
        return memoryFD$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t memoryFD
     * }
     */
    public static int memoryFD(MemorySegment struct) {
        return struct.get(memoryFD$LAYOUT, memoryFD$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t memoryFD
     * }
     */
    public static void memoryFD(MemorySegment struct, int fieldValue) {
        struct.set(memoryFD$LAYOUT, memoryFD$OFFSET, fieldValue);
    }

    private static final OfLong allocationSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("allocationSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t allocationSize
     * }
     */
    public static final OfLong allocationSize$layout() {
        return allocationSize$LAYOUT;
    }

    private static final long allocationSize$OFFSET = $LAYOUT.byteOffset(groupElement("allocationSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t allocationSize
     * }
     */
    public static final long allocationSize$offset() {
        return allocationSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t allocationSize
     * }
     */
    public static long allocationSize(MemorySegment struct) {
        return struct.get(allocationSize$LAYOUT, allocationSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t allocationSize
     * }
     */
    public static void allocationSize(MemorySegment struct, long fieldValue) {
        struct.set(allocationSize$LAYOUT, allocationSize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

