// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef WGPUSurfaceSourceWaylandSurface WGPUSurfaceDescriptorFromWaylandSurface
 * }
 */
public class WGPUSurfaceDescriptorFromWaylandSurface extends WGPUSurfaceSourceWaylandSurface {

    WGPUSurfaceDescriptorFromWaylandSurface() {
        // Should not be called directly
    }
}

