// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUImageCopyExternalTexture {
 *     WGPUChainedStruct *nextInChain;
 *     WGPUExternalTexture externalTexture;
 *     WGPUOrigin3D origin;
 *     WGPUExtent2D naturalSize;
 * }
 * }
 */
public class WGPUImageCopyExternalTexture {

    WGPUImageCopyExternalTexture() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        webgpu_h.C_POINTER.withName("nextInChain"),
        webgpu_h.C_POINTER.withName("externalTexture"),
        WGPUOrigin3D.layout().withName("origin"),
        WGPUExtent2D.layout().withName("naturalSize"),
        MemoryLayout.paddingLayout(4)
    ).withName("WGPUImageCopyExternalTexture");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = $LAYOUT.byteOffset(groupElement("nextInChain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final AddressLayout externalTexture$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("externalTexture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUExternalTexture externalTexture
     * }
     */
    public static final AddressLayout externalTexture$layout() {
        return externalTexture$LAYOUT;
    }

    private static final long externalTexture$OFFSET = $LAYOUT.byteOffset(groupElement("externalTexture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUExternalTexture externalTexture
     * }
     */
    public static final long externalTexture$offset() {
        return externalTexture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUExternalTexture externalTexture
     * }
     */
    public static MemorySegment externalTexture(MemorySegment struct) {
        return struct.get(externalTexture$LAYOUT, externalTexture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUExternalTexture externalTexture
     * }
     */
    public static void externalTexture(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(externalTexture$LAYOUT, externalTexture$OFFSET, fieldValue);
    }

    private static final GroupLayout origin$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("origin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUOrigin3D origin
     * }
     */
    public static final GroupLayout origin$layout() {
        return origin$LAYOUT;
    }

    private static final long origin$OFFSET = $LAYOUT.byteOffset(groupElement("origin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUOrigin3D origin
     * }
     */
    public static final long origin$offset() {
        return origin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUOrigin3D origin
     * }
     */
    public static MemorySegment origin(MemorySegment struct) {
        return struct.asSlice(origin$OFFSET, origin$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUOrigin3D origin
     * }
     */
    public static void origin(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, origin$OFFSET, origin$LAYOUT.byteSize());
    }

    private static final GroupLayout naturalSize$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("naturalSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUExtent2D naturalSize
     * }
     */
    public static final GroupLayout naturalSize$layout() {
        return naturalSize$LAYOUT;
    }

    private static final long naturalSize$OFFSET = $LAYOUT.byteOffset(groupElement("naturalSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUExtent2D naturalSize
     * }
     */
    public static final long naturalSize$offset() {
        return naturalSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUExtent2D naturalSize
     * }
     */
    public static MemorySegment naturalSize(MemorySegment struct) {
        return struct.asSlice(naturalSize$OFFSET, naturalSize$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUExtent2D naturalSize
     * }
     */
    public static void naturalSize(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, naturalSize$OFFSET, naturalSize$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

