// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUAdapterPropertiesMemoryHeaps {
 *     WGPUChainedStruct chain;
 *     size_t heapCount;
 *     const WGPUMemoryHeapInfo *heapInfo;
 * }
 * }
 */
public class WGPUAdapterPropertiesMemoryHeaps {

    WGPUAdapterPropertiesMemoryHeaps() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG.withName("heapCount"),
        webgpu_h.C_POINTER.withName("heapInfo")
    ).withName("WGPUAdapterPropertiesMemoryHeaps");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong heapCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("heapCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t heapCount
     * }
     */
    public static final OfLong heapCount$layout() {
        return heapCount$LAYOUT;
    }

    private static final long heapCount$OFFSET = $LAYOUT.byteOffset(groupElement("heapCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t heapCount
     * }
     */
    public static final long heapCount$offset() {
        return heapCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t heapCount
     * }
     */
    public static long heapCount(MemorySegment struct) {
        return struct.get(heapCount$LAYOUT, heapCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t heapCount
     * }
     */
    public static void heapCount(MemorySegment struct, long fieldValue) {
        struct.set(heapCount$LAYOUT, heapCount$OFFSET, fieldValue);
    }

    private static final AddressLayout heapInfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("heapInfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUMemoryHeapInfo *heapInfo
     * }
     */
    public static final AddressLayout heapInfo$layout() {
        return heapInfo$LAYOUT;
    }

    private static final long heapInfo$OFFSET = $LAYOUT.byteOffset(groupElement("heapInfo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUMemoryHeapInfo *heapInfo
     * }
     */
    public static final long heapInfo$offset() {
        return heapInfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUMemoryHeapInfo *heapInfo
     * }
     */
    public static MemorySegment heapInfo(MemorySegment struct) {
        return struct.get(heapInfo$LAYOUT, heapInfo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUMemoryHeapInfo *heapInfo
     * }
     */
    public static void heapInfo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(heapInfo$LAYOUT, heapInfo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

