// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUCompatibilityModeLimits {
 *     WGPUChainedStruct chain;
 *     uint32_t maxStorageBuffersInVertexStage;
 *     uint32_t maxStorageTexturesInVertexStage;
 *     uint32_t maxStorageBuffersInFragmentStage;
 *     uint32_t maxStorageTexturesInFragmentStage;
 * }
 * }
 */
public class WGPUCompatibilityModeLimits {

    WGPUCompatibilityModeLimits() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_INT.withName("maxStorageBuffersInVertexStage"),
        webgpu_h.C_INT.withName("maxStorageTexturesInVertexStage"),
        webgpu_h.C_INT.withName("maxStorageBuffersInFragmentStage"),
        webgpu_h.C_INT.withName("maxStorageTexturesInFragmentStage")
    ).withName("WGPUCompatibilityModeLimits");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfInt maxStorageBuffersInVertexStage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxStorageBuffersInVertexStage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInVertexStage
     * }
     */
    public static final OfInt maxStorageBuffersInVertexStage$layout() {
        return maxStorageBuffersInVertexStage$LAYOUT;
    }

    private static final long maxStorageBuffersInVertexStage$OFFSET = $LAYOUT.byteOffset(groupElement("maxStorageBuffersInVertexStage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInVertexStage
     * }
     */
    public static final long maxStorageBuffersInVertexStage$offset() {
        return maxStorageBuffersInVertexStage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInVertexStage
     * }
     */
    public static int maxStorageBuffersInVertexStage(MemorySegment struct) {
        return struct.get(maxStorageBuffersInVertexStage$LAYOUT, maxStorageBuffersInVertexStage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInVertexStage
     * }
     */
    public static void maxStorageBuffersInVertexStage(MemorySegment struct, int fieldValue) {
        struct.set(maxStorageBuffersInVertexStage$LAYOUT, maxStorageBuffersInVertexStage$OFFSET, fieldValue);
    }

    private static final OfInt maxStorageTexturesInVertexStage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxStorageTexturesInVertexStage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInVertexStage
     * }
     */
    public static final OfInt maxStorageTexturesInVertexStage$layout() {
        return maxStorageTexturesInVertexStage$LAYOUT;
    }

    private static final long maxStorageTexturesInVertexStage$OFFSET = $LAYOUT.byteOffset(groupElement("maxStorageTexturesInVertexStage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInVertexStage
     * }
     */
    public static final long maxStorageTexturesInVertexStage$offset() {
        return maxStorageTexturesInVertexStage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInVertexStage
     * }
     */
    public static int maxStorageTexturesInVertexStage(MemorySegment struct) {
        return struct.get(maxStorageTexturesInVertexStage$LAYOUT, maxStorageTexturesInVertexStage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInVertexStage
     * }
     */
    public static void maxStorageTexturesInVertexStage(MemorySegment struct, int fieldValue) {
        struct.set(maxStorageTexturesInVertexStage$LAYOUT, maxStorageTexturesInVertexStage$OFFSET, fieldValue);
    }

    private static final OfInt maxStorageBuffersInFragmentStage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxStorageBuffersInFragmentStage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInFragmentStage
     * }
     */
    public static final OfInt maxStorageBuffersInFragmentStage$layout() {
        return maxStorageBuffersInFragmentStage$LAYOUT;
    }

    private static final long maxStorageBuffersInFragmentStage$OFFSET = $LAYOUT.byteOffset(groupElement("maxStorageBuffersInFragmentStage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInFragmentStage
     * }
     */
    public static final long maxStorageBuffersInFragmentStage$offset() {
        return maxStorageBuffersInFragmentStage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInFragmentStage
     * }
     */
    public static int maxStorageBuffersInFragmentStage(MemorySegment struct) {
        return struct.get(maxStorageBuffersInFragmentStage$LAYOUT, maxStorageBuffersInFragmentStage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageBuffersInFragmentStage
     * }
     */
    public static void maxStorageBuffersInFragmentStage(MemorySegment struct, int fieldValue) {
        struct.set(maxStorageBuffersInFragmentStage$LAYOUT, maxStorageBuffersInFragmentStage$OFFSET, fieldValue);
    }

    private static final OfInt maxStorageTexturesInFragmentStage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxStorageTexturesInFragmentStage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInFragmentStage
     * }
     */
    public static final OfInt maxStorageTexturesInFragmentStage$layout() {
        return maxStorageTexturesInFragmentStage$LAYOUT;
    }

    private static final long maxStorageTexturesInFragmentStage$OFFSET = $LAYOUT.byteOffset(groupElement("maxStorageTexturesInFragmentStage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInFragmentStage
     * }
     */
    public static final long maxStorageTexturesInFragmentStage$offset() {
        return maxStorageTexturesInFragmentStage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInFragmentStage
     * }
     */
    public static int maxStorageTexturesInFragmentStage(MemorySegment struct) {
        return struct.get(maxStorageTexturesInFragmentStage$LAYOUT, maxStorageTexturesInFragmentStage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxStorageTexturesInFragmentStage
     * }
     */
    public static void maxStorageTexturesInFragmentStage(MemorySegment struct, int fieldValue) {
        struct.set(maxStorageTexturesInFragmentStage$LAYOUT, maxStorageTexturesInFragmentStage$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

