// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUSharedTextureMemoryIOSurfaceDescriptor {
 *     WGPUChainedStruct chain;
 *     void *ioSurface;
 *     WGPUBool allowStorageBinding;
 * }
 * }
 */
public class WGPUSharedTextureMemoryIOSurfaceDescriptor {

    WGPUSharedTextureMemoryIOSurfaceDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_POINTER.withName("ioSurface"),
        webgpu_h.C_INT.withName("allowStorageBinding"),
        MemoryLayout.paddingLayout(4)
    ).withName("WGPUSharedTextureMemoryIOSurfaceDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final AddressLayout ioSurface$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ioSurface"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *ioSurface
     * }
     */
    public static final AddressLayout ioSurface$layout() {
        return ioSurface$LAYOUT;
    }

    private static final long ioSurface$OFFSET = $LAYOUT.byteOffset(groupElement("ioSurface"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *ioSurface
     * }
     */
    public static final long ioSurface$offset() {
        return ioSurface$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *ioSurface
     * }
     */
    public static MemorySegment ioSurface(MemorySegment struct) {
        return struct.get(ioSurface$LAYOUT, ioSurface$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *ioSurface
     * }
     */
    public static void ioSurface(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ioSurface$LAYOUT, ioSurface$OFFSET, fieldValue);
    }

    private static final OfInt allowStorageBinding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("allowStorageBinding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool allowStorageBinding
     * }
     */
    public static final OfInt allowStorageBinding$layout() {
        return allowStorageBinding$LAYOUT;
    }

    private static final long allowStorageBinding$OFFSET = $LAYOUT.byteOffset(groupElement("allowStorageBinding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool allowStorageBinding
     * }
     */
    public static final long allowStorageBinding$offset() {
        return allowStorageBinding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool allowStorageBinding
     * }
     */
    public static int allowStorageBinding(MemorySegment struct) {
        return struct.get(allowStorageBinding$LAYOUT, allowStorageBinding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool allowStorageBinding
     * }
     */
    public static void allowStorageBinding(MemorySegment struct, int fieldValue) {
        struct.set(allowStorageBinding$LAYOUT, allowStorageBinding$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

