// Generated by jextract

package com.periut.webgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUStaticSamplerBindingLayout {
 *     WGPUChainedStruct chain;
 *     WGPUSampler sampler;
 *     uint32_t sampledTextureBinding;
 * }
 * }
 */
public class WGPUStaticSamplerBindingLayout {

    WGPUStaticSamplerBindingLayout() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_POINTER.withName("sampler"),
        webgpu_h.C_INT.withName("sampledTextureBinding"),
        MemoryLayout.paddingLayout(4)
    ).withName("WGPUStaticSamplerBindingLayout");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final AddressLayout sampler$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sampler"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUSampler sampler
     * }
     */
    public static final AddressLayout sampler$layout() {
        return sampler$LAYOUT;
    }

    private static final long sampler$OFFSET = $LAYOUT.byteOffset(groupElement("sampler"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUSampler sampler
     * }
     */
    public static final long sampler$offset() {
        return sampler$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUSampler sampler
     * }
     */
    public static MemorySegment sampler(MemorySegment struct) {
        return struct.get(sampler$LAYOUT, sampler$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUSampler sampler
     * }
     */
    public static void sampler(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sampler$LAYOUT, sampler$OFFSET, fieldValue);
    }

    private static final OfInt sampledTextureBinding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sampledTextureBinding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t sampledTextureBinding
     * }
     */
    public static final OfInt sampledTextureBinding$layout() {
        return sampledTextureBinding$LAYOUT;
    }

    private static final long sampledTextureBinding$OFFSET = $LAYOUT.byteOffset(groupElement("sampledTextureBinding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t sampledTextureBinding
     * }
     */
    public static final long sampledTextureBinding$offset() {
        return sampledTextureBinding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t sampledTextureBinding
     * }
     */
    public static int sampledTextureBinding(MemorySegment struct) {
        return struct.get(sampledTextureBinding$LAYOUT, sampledTextureBinding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t sampledTextureBinding
     * }
     */
    public static void sampledTextureBinding(MemorySegment struct, int fieldValue) {
        struct.set(sampledTextureBinding$LAYOUT, sampledTextureBinding$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

